<!-- EMAIL DE CONFIRMAÇÂO -->
<table class="ecxMsoNormalTable" border="0" cellspacing="0" cellpadding="0" width="600" style="width:450.0pt;background:white;">
    <tbody>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <a name="Logo" target="_blank"></a>
                <a href="http://www.grupocapitalponto.com.br" target="_blank">
                    <span style="text-decoration:none;">
                        <img border="0" width="180" height="49" id="ecx_x0000_i1027" src="http://www.grupocapitalponto.com.br/img/email/logo.png" alt="Mint">
                    </span>
                </a>
            </p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <span style="font-size:21.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black;"<b>Bem vindo ao Senna.</b> <br></span>
                <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                    Ola <?php echo $this->nome;?> você foi cadastrado no sistema Senna.<br>
                    Agora você tambem faz parte do Grupo Capital Ponto.<br>
                    Estamos muito felizes em telo conosco.Vista seu macação e vamos nessa.<br><br>
                </span>
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <img border="0" width="327" height="108" id="ecx_x0000_i1028" src="http://www.grupocapitalponto.com.br/img/email/imagem_sistema.gif" alt="Mint on device screens">
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <img border="0" width="580" height="1" id="ecx_x0000_i1029" src="http://www.grupocapitalponto.com.br/img/email/linha.gif">
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="" align="center" style="text-align:center;margin-bottom: 0px!important;">
                <img border="0" width="32" height="32" id="ecx_x0000_i1037" src="http://www.grupocapitalponto.com.br/img/email/envelope.gif" alt="Mail">
            </p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;margin-bottom: 0px!important;">
                <span style="font-size:13.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black;">Confirme seu e-mail para continuar</span> </p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;margin-bottom: 0px!important;">
                <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                    Para ter acesso a todas as ferramentas do sistema precisamos <br>
                    que seu e-mail seja confirmado.<br>
                </span>
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"><img border="0" width="32" height="32" id="ecx_x0000_i1039" src="http://www.grupocapitalponto.com.br/img/email/cadeado.gif" alt="Lock"></p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"> <span style="font-size:13.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black;">Segurança em primeiro lugar</span> </p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"><span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">Verificamos este e-mail antes de lhe enviar,<br>ele esta livre de qualquer tipo de virus.<br>E todas as informações e transações dentro <br> Senna estão protegidas e criptografadas.</span> </p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <a name="Login_Now" target="_blank"></a>
                <a href="http://127.0.0.1:8181<?php /*echo  $this->url('usuario-ativacao', array('key'=>$this->chaveAtivacao));*/ ?>" target="_blank">
                    <span style="color:#4DC5E2;text-decoration:none;">
                        <img border="0" width="138" height="45" id="ecx_x0000_i1041" src="http://grupocapitalponto.com.br/img/email/confirme.gif" alt="Login Now">
                    </span>
                </a>
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"><img border="0" width="580" height="1" id="ecx_x0000_i1042" src="http://www.grupocapitalponto.com.br/img/email/linha.gif"></p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"><img border="0" width="32" height="32" id="ecx_x0000_i1031" src="http://www.grupocapitalponto.com.br/img/email/link.gif" alt="Link"></p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"> <span style="font-size:13.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black;">Dados de acesso</span> </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
            <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                Usuario:
            </span>
            <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                    <b><?php echo $this->nome;?></b>
            </span>
            </p>
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
            <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                Senha:
            </span>
            <span style="font-size:10.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                   <b> <?php echo $this->senha;?></b>
            </span>
            </p>
        </td>
    </tr>
    <tr>
        <td style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;"><img border="0" width="580" height="1" id="ecx_x0000_i1044" src="http://www.grupocapitalponto.com.br/img/email/linha.gif"></p>
        </td>
    </tr>
    <tr>
        <td valign="top" style="padding:0cm 0cm 0cm 0cm;">
            <p class="ecxMsoNormal" align="center" style="text-align:center;">
                <span style="font-size:8.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999;">
                    Esta mensagem foi enviada para <a href="mailto:<?php echo $this->email;?>"><?php echo $this->email;?></a><br>Se voccê gostaria de atualizar o endereço de e-mail por favor <a name="ManageAccount" target="_blank"></a><a href="http://#" target="_blank"><span style="color:#999999;">clique&nbsp;aqui</span></a>.<br>Se você não quiser mais receber e-mails do Senna,&nbsp;<a name="Unsubscribe" target="_blank"></a><a href="https://#" target="_blank"><span style="color:#999999;">clique&nbsp;aqui</span></a>.<br>©2015 - 2015 Senna (Melbourne) | All Rights&nbsp;Reserved.<br>Senna.com.br Rua João Chaves 725,Curitiba - Xaxim, PR&nbsp;<br><a name="Privacy" target="_blank"></a><a href="#" target="_blank"><span style="color:#999999;">Politica de privacidade</span></a> | <a name="Terms" target="_blank"></a><a href="http://#" target="_blank"><span style="color:#999999;">Termos e&nbsp;Condições</span></a></span></p>
        </td>
    </tr>
    </tbody>
</table>