<li class='categoria ' meta=''>
	<a
	rel='menu_categoria_os'
	class='returnFalse arrow-right'
	key='46'
	class='item'>
		<span>
			<span class='label'>Cadastros de Serviços </span>
		</span>
	</a>
    <ul>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_servico/servicos' rel='menu_item_ordem_servico_cadastros'
        	target='panel'
        	key='47'
        	class='item'>
	        	<span>
	        		<i class='icon-wrench2 menu_icon'></i>
	        		<span class='label'>Gerenciar Serviços </span>
	        	</span>
	        </a>
        </li>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_servico/servicos_tabelas' rel='menu_item_ordem_servico_servicos_tabelas'
        	target='panel'
        	key='48'
        	class='item'>
	        	<span>
	        		<i class='icon-service-table menu_icon'></i>
	        		<span class='label'>Tabela de Serviços </span>
	        	</span>
	        </a>
        </li>

    </ul>
</li>