<li class='categoria ' meta=''>

	<a
	rel='menu_categoria_tributacao'
	class='returnFalse arrow-right'
	key='58'
	class='item'>
		<span>
			<span class='label'>Tributação </span>
		</span>
	</a>

    <ul>
        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_cadastro/tributacoes'
        	rel='menu_item_cadastro_tributacao'
        	target='panel'
        	key='60'
        	class='item'>
	        	<span>
	        		<i class='icon-box-tax menu_icon'></i>
	        		<span class='label'>Tributos de Mercadorias (NCM) </span>
	        	</span>
	        </a>
        </li>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_ancoras/tributos_auxiliares'
        	rel='menu_item_cadastro_trib_aux'
        	target='window'
        	key='109'
        	item_group='true'
        	class='item'>
	        	<span>
	        		<i class='icon-percent-attachment menu_icon'></i>
	        		<span class='label'>Cadastros Tributários Auxiliares </span>
	        	</span>
	        </a>
        </li>

    </ul>
</li>