<li class='categoria ' meta=''>
    <a rel='menu_categoria_produtos' class='returnFalse arrow-right' key='40' class='item'>
        <span>
            <span class='label'>Cadastros de Produtos </span>
        </span>
    </a>
    <ul>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_produto/produtos'
            rel='menu_item_produto_cadastro'
            target='panel'
            key='41'
            class='item'>
                <span>
                    <i class='icon-product menu_icon'></i>
                    <span class='label'>Gerenciar Produtos </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_nao_fiscal/ajustes_estoque'
            rel='menu_item_cadastro_ajuste_estoque'
            target='panel'
            key='85'
            class='item'>
                <span>
                    <i class='icon-box-adjust menu_icon'></i>
                    <span class='label'>Ajuste de Estoque </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/ancoras/cadastrosauxiliares'
            id='menu_ancoras/cadastros_auxiliares_produtos'
            rel='menu_item_cadastros_aux_produtos'
            target='window'
            key='114'
            item_group='true'
            class='item'>
                <span>
                    <i class='icon-stack-plus menu_icon'></i>
                    <span class='label'>Cadastros Auxiliares de itens de venda </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ancoras/valores_venda'
            rel='menu_item_cadastro_valores_venda'
            target='window'
            key='107'
            item_group='true'
            class='item'>
                <span>
                    <i class='icon-coins menu_icon'></i>
                    <span class='label'>Valores de Venda </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_cadastro/gerar_etiquetas'
            rel='menu_item_cadastro_gerar_etiquetas'
            target='window'
            key='76'
            class='item'>
                <span>
                    <i class='icon-tag-barcode menu_icon'></i>
                    <span class='label'>Etiquetas </span>
                </span>
            </a>
        </li>

    </ul>
</li>