<li class='categoria ' meta=''>
	<a
	rel='menu_item_usuarios'
	class='returnFalse arrow-right'
	key='49'
	class='item'>
		<span>
			<span class='label'>Usuários e Vendedores </span>
		</span>
	</a>
    <ul>
        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_usuario/funcionariosLinkCheck'
        	rel='menu_item_usuario_funcionarios'
        	target='panel'
        	key='50'
        	class='item'>
	        	<span>
	        		<i class='icon-users menu_icon'></i>
	        		<span class='label'>Gerenciar Usuários </span>
	        	</span>
	        </a>
        </li>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_usuario/perfis'
        	rel='menu_item_usuario_perfis'
        	target='panel'
        	key='51'
        	class='item'>
	        	<span>
	        		<i class='icon-key menu_icon'></i>
	        		<span class='label'>Perfis de Acesso </span>
	        	</span>
	        </a>
        </li>

    </ul>
</li>