<li class='categoria' meta=''>

    <a rel='menu_categoria_ecommerce' class='returnFalse' key='88' class='item'>
        <span>
            <span class='label'>Loja Virtual </span>
        </span>
    </a>

    <ul>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ecommerce/pedidos_ecommerce'
            rel='menu_item_pedido_ecommerce'
            target='panel'
            key='90'
            class='item'>
            <span><i class='icon-loja-pedidos menu_icon'></i>
                <span class='label'>Pedidos de Loja Virtual </span>
            </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ecommerce/sincronizacoes'
            rel='menu_item_sinc_ecommerce'
            target='window'
            key='96'
            class='item'>
                <span><i class='icon-loja-sincroniza menu_icon'></i>
                    <span class='label'>Sincronizações Loja Virtual </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ecommerce/configuracoes_ecommerce'
            rel='menu_item_config_ecommerce'
            target='window'
            key='89'
            class='item'>
                <span>
                    <i class='icon-loja-config menu_icon'></i>
                    <span class='label'>Configurações da Loja Virtual </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ecommerce/configuracoes_ecommerce/admin'
            rel='menu_item_login_ecommerce'
            target='_blank'
            key='98'
            class='item'>
                <span>
                    <i class='icon-loja-admin menu_icon'></i>
                    <span class='label'>Acessar Administração da Loja </span>
                </span>
            </a>
        </li>

    </ul>
</li>