 <li class='categoria ' meta=''>
 	<a
 	rel='menu_categoria_financeiro'
 	class='returnFalse arrow-right'
 	key='54'
 	class='item'>
	 	<span>
	 		<span class='label'>Cadastros Financeiros </span>
	 	</span>
	 </a>
    <ul>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_financeiro/lancamentos'
        	rel='menu_item_financeiro_cadastro_lancamentos'
        	target='panel'
        	key='13'
        	class='item'>
	        	<span>
	        		<i class='icon-dollar menu_icon'></i>
	        		<span class='label'>Contas a Pagar e Receber </span>
	        	</span>
	        </a>
        </li>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_ancoras/financeiro_lote'
        	rel='menu_item_financeiro_lancamento_massa'
        	target='window'
        	key='112'
        	class='item'>
	        	<span>
	        		<i class='icon-money menu_icon'></i>
	        		<span class='label'>Confirmar Lançamentos </span>
	        	</span>
	        </a>
        </li>

        <li class='item ' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_ancoras/opcoes_financeiras'
        	rel='menu_item_opcoes_financeiras'
        	target='window'
        	key='118'
        	item_group='true'
        	class='item'>
	        	<span>
	        		<i class='icon-resellerhosting menu_icon'></i>
	        		<span class='label'>Opções Financeiras </span>
	        	</span>
	        </a>
        </li>

    </ul>
</li>