 <li class='categoria ' meta=''>
 	<a
 	rel='menu_categoria_preferencias'
 	class='returnFalse'
 	key='70'
 	class='item'>
	 	<span>
	 		<span class='label'>Preferências </span>
	 	</span>
	 </a>
    <ul>

        <li class='item ' meta=''>
        	<a 
        	href='/senna/zf2/config/manutencao'
        	id='menu_config/manutencao'
        	rel='menu_item_manutencao'
        	target='modal'
        	key='84'
        	class='item'>
        	<span>
        		<i class='icon-screwdriver menu_icon'></i>
        		<span class='label'>Manutenção </span>
        	</span>
        	</a>
        </li>
        <li class='item ' meta=''>
        	<a
        	href='/senna/zf2/config/opcoes_pdv'
        	id='menu_config/opcoes_pdv'
        	rel='menu_item_config_preferencias_pdv'
        	target='modal'
        	key='72'
        	class='item'>
	        	<span>
	        		<i class='icon-puzzle menu_icon'></i>
	        		<span class='label'>Opções do PDV </span>
	        	</span>
	        </a>
        </li>
        <li class='item ' meta=''>
        	<a
        	href='/senna/zf2/config/opcoes_erp'
        	id='menu_config/opcoes_erp'
        	rel='menu_item_config_preferencias'
        	target='modal'
        	key='71'
        	class='item'>
	        	<span>
	        		<i class='icon-cog menu_icon'></i>
	        		<span class='label'>Opções do Sistema </span>
	        	</span>
	        </a>
        </li>

    </ul>
</li>