<li class='categoria ' meta=''>
	<a rel='menu_categoria_consultas' class='returnFalse' key='12' class='item'>
		<span>
			<span class='label'>Consultas e Acompanhamentos</span>
		</span>
	</a>
    <ul>

        <li class='item' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_cadastro/acompanhamento_notas'
        	rel='menu_item_acompanhamento_notas'
        	target='window'
        	key='80'
        	class='item'>
	        	<span>
	        		<i class='icon-eye menu_icon'></i>
	        		<span class='label'>Acompanhamento NF-e/NFS-e </span>
	        	</span>
	        </a>
        </li>

        <li class='item' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_venda/caixas'
        	rel='menu_item_caixas'
        	target='panel'
        	key='74'
        	class='item'>
        		<span>
        			<i class='icon-money-drawer menu_icon'></i>
        			<span class='label'>Visualizar Caixas do PDV </span>
        		</span>
        	</a>
        </li>

        <li class='item' meta=''>
        	<a
        	href='<?php echo $this->basePath() ?>/senna/negado'
        	id='menu_relatorio/relatorios'
        	rel='menu_item_relatorios'
        	target='panel'
        	key='14'
        	item_group='true'
        	shortcut='alt+shift+r'
        	class='item'>
        		<span>
        			<i class='icon-bars menu_icon'></i>
        			<span class='label'>Relatórios
        				<span class='shortcut'>alt+shift+r</span>
        			</span>
        		</span>
        	</a>
        </li>

    </ul>
</li>