<li class='categoria ' meta=''>
    <a rel='menu_categoria_cadastro' class='returnFalse' key='30' class='item'>
        <span>
            <span class='label'>Cadastros</span>
        </span>
    </a>
    <ul>
        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ancoras/dados'
            rel='menu_item_cadastro_importacao'
            target='panel'
            key='77'
            class='item'>
                <span>
                    <i class='icon-database menu_icon'></i>
                    <span class='label'>Importação/Exportação de Dados </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_cadastro/clientes'
            rel='menu_item_cadastro_clientes'
            target='panel'
            key='31'
            class='item'>
                <span>
                    <i class='icon-address-book menu_icon'></i>
                    <span class='label'>Clientes </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_cadastro/empresas'
            rel='menu_item_cadastro_empresa'
            target='window'
            key='69'
            class='item'>
                <span>
                    <i class='icon-building menu_icon'></i>
                    <span class='label'>Dados da sua Empresa </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_cadastro/fornecedores'
            rel='menu_item_cadastro_fornecedores'
            target='panel'
            key='32'
            class='item'>
                <span>
                    <i class='icon-provider menu_icon'></i>
                    <span class='label'>Fornecedores </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_cadastro/transportadoras'
            rel='menu_item_cadastro_transportadoras'
            target='panel'
            key='33'
            class='item'>
                <span>
                    <i class='icon-truck menu_icon'></i>
                    <span class='label'>Transportadoras </span>
                </span>
            </a>
        </li>

        <li class='item ' meta=''>
            <a
            href='<?php echo $this->basePath() ?>/senna/negado'
            id='menu_ancoras/cadastros_auxiliares'
            rel='menu_item_cadastros_auxiliares'
            target='window'
            key='108'
            item_group='true'
            class='item'>
                <span>
                    <i class='icon-attachment menu_icon'></i>
                    <span class='label'>Cadastros Auxiliares </span>
                </span>
            </a>
        </li>

    </ul>
</li>