<li class='categoria ' meta='compras'>
	<a rel='menu_categoria_compra' class='returnFalse' key='10' class='item'>
		<span>
			<span class='label'>Compras </span>
		</span>
	</a>
	<ul>
	    <li class='item ' meta=''>
	    	<a
	    	href='<?php echo $this->basePath() ?>/senna/negado'
	    	id='menu_cadastro/pedidos_compra'
	    	rel='menu_item_cadastro_pedidos_compra'
	    	target='panel'
	    	key='103'
	    	class='item'>
		    	<span>
		    		<i class='icon-cart-add menu_icon'></i>
		    		<span class='label'>Pedidos de Compra </span>
		    	</span>
	    	</a>
	    </li>

	    <li class='item ' meta=''>
	    	<a
	    	href='<?php echo $this->basePath() ?>/senna/negado'
	    	id='menu_ancoras/realizar_compra'
	    	rel='menu_item_realizar_compra'
	    	target='window'
	    	key='110'
	    	item_group='true'
	    	class='item'>
	    		<span>
	    			<i class='icon-cart-plus menu_icon'></i>
	    			<span class='label'>Registrar Compra </span>
	    		</span>
	    	</a>
	    </li>
	</ul>
</li>