<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Usuario\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'sobrenome', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'login', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'senha', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'ativo', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'chaveAtivacao', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'atualizacao', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'criado');
        }

        return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'sobrenome', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'login', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'senha', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'ativo', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'chaveAtivacao', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'atualizacao', '' . "\0" . 'Usuario\\Entity\\Usuario' . "\0" . 'criado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriado', array());

        return parent::getCriado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriado', array());

        return parent::setCriado();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtualizacao', array());

        return parent::getAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtualizacao', array());

        return parent::setAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getChaveAtivacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChaveAtivacao', array());

        return parent::getChaveAtivacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setChaveAtivacao($chaveAtivacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChaveAtivacao', array($chaveAtivacao));

        return parent::setChaveAtivacao($chaveAtivacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptSenha', array($senha));

        return parent::encryptSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getSobrenome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSobrenome', array());

        return parent::getSobrenome();
    }

    /**
     * {@inheritDoc}
     */
    public function setSobrenome($sobrenome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSobrenome', array($sobrenome));

        return parent::setSobrenome($sobrenome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
