<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv='cache-control' content='no-cache'/>
    <meta http-equiv='expires' content='0'/>
    <meta http-equiv='pragma' content='no-cache'/>
    <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    <meta name="base_url" content=""/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <!-- Script da pagina js/code -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/mootools-1.2-core.js')
        ->appendFile($this->basePath() . '/js/mootools-1.2-more.js')
        ->appendFile($this->basePath() . '/js/Core.js')
        ->appendFile($this->basePath() . '/js/Window.js')
        ->appendFile($this->basePath() . '/js/Modal.js')
        ->appendFile($this->basePath() . '/js/mocha-ext.js')
        ->appendFile($this->basePath() . '/js/base.js')
        ->appendFile($this->basePath() . '/js/atalhos.js')
        ->appendFile($this->basePath() . '/js/detect-zoom.js')
        ->appendFile($this->basePath() . '/js/jquery/core.js')
        ->appendFile($this->basePath() . '/js/jquery/dump.js')
        ->appendFile($this->basePath() . '/js/jquery/debug.js')
        ->appendFile($this->basePath() . '/js/jquery/bt.js')
        ->appendFile($this->basePath() . '/js/jquery/validate.js')
        ->appendFile($this->basePath() . '/js/jquery/maskedinput.js')
        ->appendFile($this->basePath() . '/js/jquery/uppercase.js')
        ->appendFile($this->basePath() . '/js/jquery/clonefield.js')
        ->appendFile($this->basePath() . '/js/jquery/tab.js')
        ->appendFile($this->basePath() . '/js/jquery/tablestyle.js')
        ->appendFile($this->basePath() . '/js/jquery/date.js')
        ->appendFile($this->basePath() . '/js/jquery/datepicker.js')
        ->appendFile($this->basePath() . '/js/jquery/readonly.js')
        ->appendFile($this->basePath() . '/js/sexyalertbox.js')
        ->appendFile($this->basePath() . '/js/jquery/confirm_message.js')
        ->appendFile($this->basePath() . '/js/jquery/livequery.js')
        ->appendFile($this->basePath() . '/js/forms.js')
        ->appendFile($this->basePath() . '/js/jquery/priceformat.js')
        ->appendFile($this->basePath() . '/js/jquery/cloneform.js')
        ->appendFile($this->basePath() . '/js/jquery/ui.js')
        ->appendFile($this->basePath() . '/js/jquery/autosuggest.js')
        ->appendFile($this->basePath() . '/js/jquery/barcode.js')
        ->appendFile($this->basePath() . '/js/jquery/clonetable.js')
        ->appendFile($this->basePath() . '/js/jquery/uploader.js')
        ->appendFile($this->basePath() . '/js/script_usuario_form.js')?>




    <!-- Estilos da pagina Css/code -->
    <?php echo $this->headLink()
        //->appendStylesheet($this->basePath() . '/css/noprint.css')
        ->appendStylesheet($this->basePath() . '/css/glyphs.css')
        ->appendStylesheet($this->basePath() . '/css/loader.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/style_tagplus.css')
        ->appendStylesheet($this->basePath() . '/css/sexyalertbox.css')
        ->appendStylesheet($this->basePath() . '/css/datepicker.css')
        ->appendStylesheet($this->basePath() . '/css/cloneform.css')
        ->appendStylesheet($this->basePath() . '/css/jqueryui.css')
        ->appendStylesheet($this->basePath() . '/css/clonetable.css')
        ->appendStylesheet($this->basePath() . '/css/uploader.css') ?>

</head>

<body>
<!--Container tela.php-->
<div id="loader">
    <div class="loader-text">
        <span class='carregando'>Carregando ...</span>
        <span class='enviando' style="display: none">Enviando ...</span>
    </div>
    <div class="loader-bg">&nbsp;</div>
</div>
<div id="tela" style="height: 100%;">
    <div id="conteudo">
        <!--INICIO DO FORMULARIO-->


        <!--Container base_form.php-->
        <form action="http://app.tagplus.com.br/empresariamkk/usuario/funcionarios/save" class="form" id="form" method="post" windowId="http://app.tagplus.com.br/empresariamkk/usuario/funcionarios/form">

            <!-- BOTOES DO FORM -->
            <?php echo $this->partial('partials/form_botoes'); ?>
            <!-- -->

            <div class="form_fields" id="form_fields">
                <input id="id" name="id" type="hidden" value="1"></input>
                <!-- TAB PERFIL -->
                <?php echo $this->partial('partials/tab_perfil_acesso'); ?>
                <!-- -->

                <!-- TAB DADOS SECUNDARIOS -->
                <?php echo $this->partial('partials/tab_dados_secundarios'); ?>
                <!-- -->

                <!-- TAB CONTATO -->
                <?php echo $this->partial('partials/tab_contatos'); ?>
                <!-- -->

                <!-- TAB ENDEREÇOS -->
                <?php echo $this->partial('partials/tab_enderecos'); ?>
                <!-- -->

                <!-- TAB DEPENDENTES -->
                <?php echo $this->partial('partials/tab_dependentes'); ?>
                <!-- -->

                <!-- TAB CLIENTES -->
                <?php echo $this->partial('partials/tab_clientes'); ?>
                <!-- -->

                <!-- TAB DASHBOARD -->
                <?php echo $this->partial('partials/tab_dashboard'); ?>
                <!-- -->

                <!-- TAB UPLIOAD -->
                <?php //echo $this->partial('partials/tab_upload'); ?>
                <!-- -->
            </div>
        </form>


        <!--FIM DO FORMULARIO-->

    </div>
</div>
<div id="footer"></div>
</body>
</html>