<?php
if(isset($this->data))
{
   print json_encode($this->data);
}
else
{
    header("HTTP/1.0 500 Internal Server Error");

    echo "<h5>Atenção:</h5>
            <br/>
            <div style='max-height:270px;overflow:auto;display:block;'>
            Não é possivel concluir a operação.
            <br />
            {$this->erro} fornecido já foi cadastrado.
            </div>";
    die();
}
