<h3>Register</h3>

<?php if($this->messages):?>
    <p>
        <?php echo $this->messages[0]; ?>
    </p>

<?php else: ?>

<?php endif; ?>
    <?php
    $form = $this->form;
    $form->setAttribute('action',$this->url('usuario-registro',array('controller'=>'index','action'=>'registro')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();

    ?>



