<h1>Usuarios</h1>

<br />

<p>
    <a href="<?php echo $this->url('usuario-admin/default',array('action'=>'new')); ?>">Novo</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Perfil</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>
    
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getNome(); ?></td>
        <td><?php echo $entity->getEmail(); ?></td>
        <td><?php echo $entity->getPerfil()->getNome(); ?></td>
        <td>
            <a href="<?php echo $this->url('usuario-admin/default',
                    array('controller'=>'usuarios','action'=>'edit','id'=>$entity->getId()));?>">Editar</a>
            
            <a href="<?php echo $this->url('usuario-admin/default',
                    array('controller'=>'usuarios','action'=>'delete','id'=>$entity->getId()));?>">Delete</a>
            
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>