<!-- ERRO NO FORMULARIO-->
<?php if($this->erroForm): ?>
    <form class="col-md-4 center-margin">
        <div class="row" id="error">
            <div class="error-notice">
                <div class="oaerror danger" style="font-size: 14px">
                    <?php echo $this->message; ?>
                </div>
            </div>
        </div>
        <script> setTimeout(function(){$('#error').fadeOut(3000); },15000) </script>
    </form>
<?php endif; ?>
<!--  -->

<!-- ATENCAO NO FORMULARIO-->
<?php if($this->atencaoForm): ?>
    <form class="col-md-4 center-margin">
        <div class="row" id="atencao">
            <div class="error-notice">
                <div class="oaerror warning" style="font-size: 14px">
                    <?php echo $this->message; ?>
                </div>
            </div>
        </div>
        <script> setTimeout(function(){$('#atencao').fadeOut(3000); },15000) </script>
    </form>
<?php endif; ?>
<!--  -->

<!-- INFO NO FORMULARIO-->
<?php if($this->infoForm): ?>
    <form class="col-md-4 center-margin">
        <div class="row" id="info">
            <div class="error-notice">
                <div class="oaerror info" style="font-size: 14px">
                    <?php echo $this->message; ?>
                </div>
            </div>
        </div>
        <script> setTimeout(function(){$('#info').fadeOut(3000); },15000) </script>
    </form>
<?php endif; ?>
<!--  -->