<!-- FORM EMAIL -->
<?php $email->setAttribute('action',$this->url('usuario-authentication',array('controller'=>'Authentication','action'=>'index')))
    ->setAttribute('id','login-validation')
    ->setAttribute('class','col-md-4 center-margin')
    ->setAttribute('autocomplete','off');
$email->prepare();
echo $this->form()->openTag($email); ?>

<!-- TAB RECUPERAR SENHA -->
<?php echo $this->partial('partials/tab_recuperar_senha'); ?>
<!-- -->

<?php echo $this->form()->closeTag();?>
<!--  -->