<?php echo $this->doctype(); ?>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Senna :: Grupo Capital Ponto</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">

    <link rel="shortcut icon" href="<?php echo $this->basePath() ?>/images/favicon.ico">
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/js-core.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/script_pagina.js"></script>
    <style>
        .text-green{
            color:#4ECDC4!important
        }
        a.normal:hover {
            cursor: default;
            color: #7e7e7e;
            font-size: 13px;
        }
        a.normal {
            cursor: default;
            font-size: 13px;
        }

        #loading {
            position: fixed;
            width: 100%;
            height: 100%;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            display: block;
            background: #F5F5F5;
            z-index: 10000;
        }

        #loading img {
            position: absolute;
            top: 50%;
            left: 50%;
            margin: -23px 0 0 -23px;
        }

        .error-notice {
            margin: 10px ; /* Making sure to keep some distance from all side */
        }

        .oaerror {
            width: 100%; /* Configure it fit in your design  */
            margin: 0 auto; /* Centering Stuff */
            background-color: #FFFFFF; /* Default background */
            padding: 20px;
            border: 1px solid #eee;
            border-left-width: 5px;
            border-radius: 3px;
            margin: 0 auto;
            font-family: 'Open Sans', sans-serif;
            font-size: 16px;
        }

        .danger {
            border-left-color: #d9534f; /* Left side border color */
            background-color: rgba(217, 83, 79, 0.1); /* Same color as the left border with reduced alpha to 0.1 */
        }

        .danger strong {
            color:  #d9534f;
        }

        .warning {
            border-left-color: #f0ad4e;
            background-color: rgba(240, 173, 78, 0.1);
        }

        .warning strong {
            color: #f0ad4e;
        }

        .info {
            border-left-color: #5bc0de;
            background-color: rgba(91, 192, 222, 0.1);
        }

        .info strong {
            color: #5bc0de;
        }

        .success {
            border-left-color: #1BBC9B;
            background-color: rgba(4, 147, 114, 0.1);
        }

        .success strong {
            color: #1BBC9B;
        }
    </style>

    <?php echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/helpers-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/elements/elements-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/fontawesome/fontawesome.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/linecons/linecons.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/snippets/snippets-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/applications/mailbox.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/layout.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/layout-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/framework-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/border-radius.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/colors.css' )?>
</head>
<body>
<div id="loading"><img src="<?php echo $this->basePath() ?>/assets-minified/images/spinner/loader-dark.gif" alt="Loading..."></div>
<div class="center-vertical">
    <div class="center-content">

        <!-- PARTIAL LOGO -->
        <?php echo $this->partial('partials/tab_logo'); ?>
        <!-- -->

        <!-- ERRO COM BOTAO-->
        <?php if($this->erro): ?>

            <form class="col-md-4 center-margin">
                <div class="row" id="error">
                    <div class="error-notice">
                        <div class="oaerror danger" style="font-size: 14px">
                            <?php echo $this->message; ?>
                        </div>
                    </div>
                </div>
                <div id="div_erro" class="content-box modal-content ">
                    <div class="button-pane text-center">
                        <a href="\" class="btn btn-md btn-link " switch-target="#login-form" switch-parent="#div_erro" title="Entrar no sistema">Entrar no sistema</a>
                    </div>
                </div>
            </form>

        <?php elseif($this->sucesso): ?>

            <form class="col-md-4 center-margin">
                <div class="row" id="successo">
                    <div class="error-notice">
                        <div class="oaerror success" style="font-size: 14px">
                            <?php echo $this->message; ?>
                        </div>
                    </div>
                </div>
                <div id="div_erro" class="content-box modal-content ">
                    <div class="button-pane text-center">
                        <a href="\" class="btn btn-md btn-link " switch-target="#login-form" switch-parent="#div_erro" title="Entrar no sistema">Entrar no sistema</a>
                    </div>
                </div>
            </form>

        <?php elseif($this->atencao): ?>

            <form class="col-md-4 center-margin">
                <div class="row" id="atencao">
                    <div class="error-notice">
                        <div class="oaerror warning" style="font-size: 14px">
                            <?php echo $this->message; ?>
                        </div>
                    </div>
                </div>
                <div id="div_erro" class="content-box modal-content ">
                    <div class="button-pane text-center">
                        <a href="\" class="btn btn-md btn-link " switch-target="#login-form" switch-parent="#div_erro" title="Entrar no sistema">Entrar no sistema</a>
                    </div>
                </div>
            </form>
        <?php elseif($this->info): ?>

            <form class="col-md-4 center-margin">
                <div class="row" id="info">
                    <div class="error-notice">
                        <div class="oaerror info" style="font-size: 14px">
                            <?php echo $this->message; ?>
                        </div>
                    </div>
                </div>
                <div id="div_erro" class="content-box modal-content ">
                    <div class="button-pane text-center">
                        <a href="\" class="btn btn-md btn-link " switch-target="#login-form" switch-parent="#div_erro" title="Entrar no sistema">Entrar no sistema</a>
                    </div>
                </div>
            </form>

        <?php else: ?>

            <!-- ALERTAS-->
            <?php echo $this->partial('partials/alertas_formulario'); ?>
            <!--  -->

            <!-- PARTIAL FORM EMAIL -->
            <?php echo $this->partial('partials/form_email'); ?>
            <!--  -->

            <?php if($this->login):?>
                <!-- PARTIAL FORM USUARIO E SENHA -->
                <?php echo $this->partial('partials/form_usuario_senha'); ?>
                <!--  -->
            <?php endif?>

            <?php if($this->reset):?>
                <!-- PARTIAL FORM USUARIO E SENHA -->
                <?php echo $this->partial('partials/form_redefinir_senha'); ?>
                <!--  -->
            <?php endif?>

            <!-- PARTIAL FOOTER -->
            <?php echo $this->partial('partials/tab_footer'); ?>
            <!--  -->

        <?php endif; ?>

    </div>
</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.css">
<script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.js"></script>
</body>
</html>