<div id="login-form" class="content-box modal-content ">
    <div class="content-box-wrapper pad20A">
        <div class="form-group">
            <label for="exampleInputEmail1">Login:</label>
            <div class="input-group input-group-lg">
                <span class="input-group-addon addon-inside bg-white font-primary">
                    <i class="glyph-icon icon-user"></i>
                </span>
                <?php echo $this->formElement($input = $form->get('login'));?>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Senha:</label>
            <div class="input-group input-group-lg">
                <span class="input-group-addon addon-inside bg-white font-primary">
                    <i class="glyph-icon icon-unlock-alt"></i>
                </span>
                <?php echo $this->formElement($input = $form->get('senha'));?>
            </div>
        </div>
        <div class="row">
            <div class="checkbox-primary col-md-6" style="height: 20px">
                <label>
                    <input type="checkbox" style="display: none" id="loginCheckbox1" class="custom-checkbox">
                </label>
            </div>
            <div class="text-right col-md-6">
                <a href="#" class="switch-button" switch-target="#login-forgot" switch-parent="#login-form" title="Recover password">Esqueceu sua senha?</a>
            </div>
        </div>
    </div>
    <div class="button-pane">
        <?php echo $this->formElement($input = $form->get('entrar'));?>
    </div>
</div>
