<div id="login-forgot" class="content-box modal-content hide">
    <div class="content-box-wrapper pad20A">
        <div class="form-group">
            <label for="exampleInputEmail1">E-mail:</label>
            <div class="input-group">
                <span class="input-group-addon addon-inside bg-gray">
                    <i class="glyph-icon icon-envelope-o"></i>
                </span>
                <input type="email" class="form-control" id="email" name="email" placeholder="Digite seu e-mail">
            </div>
        </div>
    </div>
    <div class="button-pane text-center">
        <button type="submit" class="btn btn-md btn-primary">Recuperar senha</button> <a href="#" class="btn btn-md btn-link switch-button" switch-target="#login-form" switch-parent="#login-forgot" title="Cancel">Cancelar</a></div>
</div>
