<div class="tab" id="tab_dados_gerais" ref="<img src='../../images/data.png'> Dados Gerais" rel="tab_dados_gerais">
    <input id="id_funcionario" name="id_funcionario" type="hidden" value=""<?php echo __ID_USUARIO__ ?>""></input>

    <!-- TAB DADOS GERAIS -->
    <?php echo $this->partial('partials/alerta'); ?>
    <!-- -->

    <!-- SEXO  -->
    <fieldset class="fieldset " style="width:180px;">
        <legend>
            <span class="legend">
                <span class="legend_label">Sexo</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:150px; ">
            <span class="input " rel="sexo" style="">
                <?php echo $this->formElement($input = $form->get('sexo'));?>
            </span>
        </p>
    </fieldset>

    <hr class="clear" size="1"></hr>

    <!-- INFORMACOES PESSOAIS  -->
    <fieldset class="fieldset " style="width:996px;">

        <legend>
            <span class="legend">
                <span class="legend_label">Informações Pessoais</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <!-- NOME -->
        <p class="field " style="width:390px; ">
            <label class="" for="razao_social" style="">Nome</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="razao_social" style="">
                <?php echo $this->formElement($input = $form->get('nome'));?>
            </span>
        </p>

        <!-- CPF -->
        <p class="field " style="width:auto; width: 100px; ">
            <label class="" for="cpf" style="">CPF</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="cpf" style="">
                <?php echo $this->formElement($input = $form->get('cpf'));?>
            </span>
        </p>

        <!-- RG -->
        <p class="field " style="width:auto; width: 95px; margin-left:10px;">
            <label class="" for="rg" style="">RG</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="rg" style="">
                <?php echo $this->formElement($input = $form->get('rg'));?>
            </span>
        </p>

        <!-- DATA NASCIMENTO -->
        <p class="field " style="width:125px;; ">
            <label class="" for="data_nascimento" style="">Data de Nascimento </label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="data_nascimento" style="">
                <?php echo $this->formElement($input = $form->get('dataNascimento'));?>
            </span>
        </p>

        <!-- ESCOLARIDADE -->
        <p class="field " style="width:205px;; ">
            <label class="" for="escolaridade" style="">Escolaridade</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="escolaridade" style="">
                <?php echo $this->formElement($input = $form->get('escolaridade'));?>
            </span>
        </p>
    </fieldset>

    <hr class="clear" size="1"></hr>

    <!-- DADOS DE ACESSO  -->
    <fieldset class="fieldset " style="width:97%;width: 437px; float: left;">

        <legend>
            <span class="legend">
                <span class="legend_label">Dados de Acesso</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <!-- LOGIN DE ACESSO-->
        <p class="field inline" style="width:auto; width:90% !important;">
            <label class="" for="codigo_acesso" style="">Login </label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="codigo_acesso" style="">
                <?php echo $this->formElement($input = $form->get('login'));?>
            </span>
        </p>

        <!-- SENHA -->
        <p class="field inline" style="width:auto; width:90% !important;">
            <label class="" for="senha" style="">Senha</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="senha" style="">
                <?php echo $this->formElement($input = $form->get('senha'));?>
            </span>
        </p>

        <!-- CONFIRMACAO DE SENHA -->
        <p class="field inline" style="width:auto; width:90% !important;">
            <label class="" for="senha_confirma" style="">Confirmação de Senha </label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="senha_confirma" style="">
                <?php echo $this->formElement($input = $form->get('senha_confirma'));?>
            </span>
        </p>

        <!-- PERFIL DE ACESSO -->
        <p class="field inline" style="width:auto; width:90% !important;">
            <label class="" for="perfil" style="">Perfil de Acesso </label>
            <span class="input_alert">&nbsp;</span><span class="input " rel="perfil" style="">
                <?php echo $this->formElement($input = $form->get('perfil'));?>
            </span>
        </p>

    </fieldset>

    <!-- HORARIOS  -->
    <fieldset class="fieldset " style="width:250px;float:left">

        <legend>
            <span class="legend">
                <span class="legend_label">Horários</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <!-- HORA DE ENTRADA -->
        <p class="field inline" style="width:auto; ">
            <label class="" for="hora_entrada" style="">Hora de Entrada</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="hora_entrada" style="">
                <?php echo $this->formElement($input = $form->get('hora_entrada'));?>
            </span>
        </p>

        <!-- HORA ALMOCO ENTRADA -->
        <p class="field inline" style="width:auto; ">
            <label class="" for="hora_almoco_entrada" style="">Inicio do almoço</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="hora_almoco_entrada" style="">
                <?php echo $this->formElement($input = $form->get('hora_almoco_entrada'));?>
            </span>
        </p>

        <!-- HORA ALMOCO SAIDA -->
        <p class="field inline" style="width:auto; ">
            <label class="" for="hora_almoco_saida" style="">Fim do almoço</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="hora_almoco_saida" style="">
                <?php echo $this->formElement($input = $form->get('hora_almoco_saida'));?>
            </span>
        </p>

        <!-- HORA SAIDA -->
        <p class="field inline" style="width:auto; ">
            <label class="" for="hora_saida" style="">Hora de Saída</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="hora_saida" style="">
                <?php echo $this->formElement($input = $form->get('hora_saida'));?>
            </span>
        </p>

    </fieldset>

    <!-- DADOS BANCARIOS  -->
    <fieldset class="fieldset " show="inline" style="width:273px;">

        <legend>
            <span class="legend"><span class="legend_label">Dados Bancários</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <!-- TIPO DE CONTA BANCARIA  -->
        <p class="field inline" style="width:45%; ">
            <label class="" for="tipo_conta" style="">Tipo de Conta Bancária</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="tipo_conta" style="">
                <?php echo $this->formElement($input = $form->get('tipoContaBancaria'));?>
            </span>
        </p>

        <!-- TIPO AGENCIA BANCARIA  -->
        <p class="field inline" style="width:45%; ">
            <label class="" for="banco_agencia" style="">Agência Bancária</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="banco_agencia" style="">
                <?php echo $this->formElement($input = $form->get('agencia'));?>
            </span>
        </p>

        <!-- TIPO CONTA BANCARIA  -->
        <p class="field inline" style="width:45%; ">
            <label class="" for="banco_conta" style="">Conta Bancária</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="banco_conta" style="">
                <?php echo $this->formElement($input = $form->get('contaCorrente'));?>
            </span>
        </p>

        <!-- TIPO NUMERO DO BANCO  -->
        <p class="field inline" style="width:45%; ">
            <label class="" for="banco_numero" style="">Número do Banco</label>
            <span class="input_alert">&nbsp;</span><span class="input " rel="banco_numero" style="">
                <?php echo $this->formElement($input = $form->get('numerobanco'));?>
            </span>
        </p>

    </fieldset>

    <hr class="clear" size="1"></hr>

    <!-- DADOS TRABALHISTAS  -->
    <fieldset class="fieldset " show="inline" style="width:996px;">

        <legend>
            <span class="legend">
                <span class="legend_label">Dados Trabalhistas</span>
                <span class="input_alert">&nbsp;</span></span>
        </legend>

        <!-- SETOR -->
        <p class="field " style="width:260px; ">
            <label class="" for="setor" style="">Departamento</label>
            <span class="input_alert">&nbsp;</span>
            <span
                class="input " rel="setor" style="">
                <?php echo $this->formElement($input = $form->get('setor'));?>
            </span>
        </p>

        <!-- DATA ADMINISSAO -->
        <p class="field " style="width:120px; ">
            <label class="" for="data_admissao" style="">Data de Admissão
            </label><span class="input_alert">&nbsp;</span>
            <span class="input " rel="data_admissao" style="">
                <?php echo $this->formElement($input = $form->get('dataAdminissao'));?>
            </span>
        </p>

        <!-- DATA DEMISSAO -->
        <p class="field " style="width:120px; ">
            <label class="" for="data_demissao" style="">Data de Demissão
            </label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="data_demissao" style="">
                <?php echo $this->formElement($input = $form->get('dataDemissao'));?>
            </span>
        </p>

        <!-- COMISSAO -->
        <p class="field " style="width:105px; ">
            <label class="" for="comissao" style="">Comissão (%)</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="comissao" style="">
                <?php echo $this->formElement($input = $form->get('comissao'));?>
            </span>
        </p>

        <!-- DESCANSO SEMANAL -->
        <p class="field " style="width:150px; ">
            <label class="" for="descanso_semanal" style="">Descanso Semanal
            </label><span class="input_alert">&nbsp;</span>
            <span class="input " rel="descanso_semanal" style="">
                <?php echo $this->formElement($input = $form->get('descancoSemanal'));?>
            </span></p>

        <!-- CTPS -->
        <p class="field " style="width:150px; ">
            <label class="" for="ctps" style="">CTPS</label><span class="input_alert">&nbsp;</span><span
                class="input short" rel="ctps" style="">
                <?php echo $this->formElement($input = $form->get('ctps'));?>
            </span>
        </p>

    </fieldset>

    <!-- (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR  -->
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>
        &nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
</div>