<div class="tab" id="tab_upload_20101863141dac7c327ba434d0f398e75b808d5d8a" ref="Arquivos" rel="tab_upload" style="height:840px">
    <div class="uploader files" delete_url="http://app.tagplus.com.br/empresariamkk/files/delete_s3/" list_url="http://app.tagplus.com.br/empresariamkk/files/list_s3/funcionarios/1" rel="arquivo" upload_url="http://app.tagplus.com.br/empresariamkk/files/upload_s3/funcionarios/1">


        <input accept="" id="upload_arquivo" multiple="multiple" name="upload_arquivo" style="display: none;" type="file" value=""></input>
        <div class="dropbox"><span>Solte os arquivos aqui para enviar</span></div>
        <div class="thumbs_nav">
            <a class="list" title="Exibir como lista"><i class="icon-list"></i></a>
            <a class="grid" title="Exibir como grade"><i class="icon-grid2"></i></a>
            <a class="refresh" title="Atualizar listagem"><i class="icon-loop"></i></a>
            <a class="novo"><i class="icon-arrow-up2"></i> <span>Enviar Arquivos</span></a>
        </div>
        <div class="thumbs list"></div>
    </div>
    <p class="field file_manager big" style="width:auto; "><span class="input " rel="arquivo" style=""></span></p>
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
</div>