<div class="tab" id="tab_clientes_18304969017c7f27c8f2e208883f23b6071f250e0d" ref="Clientes" rel="tab_clientes">
    <div class="help_infos" id="tip_cabecalho" style=" ">
        <div style=""> Caso deseje que o funcionário venda exclusivamente para determinado(s) cliente(s), basta inseri-lo(s) abaixo. Ao realizar uma venda, se o funcionário não tiver permissão, ela não será concretizada/finalizada. Opção válida para as seguintes movimentações: Pedido/Orçamento, Venda Simples, Pré-Venda, Dav, Dav OS, NF-e e NFS-e. </div>
    </div>
    <div class="fieldset" id="select_vendas_restritas" style="width:98%">
        <fieldset class="fieldset " style="width:97%;width:97%; height:60px">
            <legend><span class="legend"><span class="legend_label">Opções</span><span class="input_alert">&nbsp;</span></span>
            </legend>

            <p class="field " style="width:auto; ">
                <label class="" for="vendas_restritas" style="">Vendas Restritas</label><span class="input_alert">&nbsp;</span><span class="input " rel="vendas_restritas" style=""><select class="" eval="1" id="vendas_restritas" name="vendas_restritas" size="1" style=""><option value="0">Esse usuário tem permissão para vender para todos clientes.</option><option value="1">Esse usuário só pode vender para o(s) cliente(s) indicado(s).</option></select></span></p>

        </fieldset>
    </div>
    <div class="fieldset" id="table_clientes_vendedores" style="width:98%">
        <fieldset class="fieldset " style="width:97%;">
            <legend><span class="legend"><span class="legend_label">Clientes</span><span class="input_alert">&nbsp;</span></span>
            </legend>

            <table borborder="0" cellpadding="0" cellspacing="0" class="form_table" id="clientes_vendedores" style="width:98%">
                <thead>
                <tr>
                    <th width="64%">Cliente</th>
                    <th width="33%">Cpf/Cnpj</th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <td>
                        <input id="cliente_vendedor__id" name="cliente_vendedor__id" type="hidden" value=""></input>
                        <input id="cliente_vendedor__id_funcionario" name="cliente_vendedor__id_funcionario" type="hidden" value="1"></input>
                        <p class="field " style="width:auto; "><span class="input " rel="cliente_vendedor__id_cliente" style=""><input id="cliente_vendedor__id_cliente" name="cliente_vendedor__id_cliente" type="hidden" value=""></input><i class="ui-autocomplete_combo" tabindex="-1"></i><input autosuggest="cliente_vendedor__id_cliente" class=" autosuggest" filters="[]" form_title="Cadastrando false" form_url="" form_url_field="" id="cliente_vendedor__id_cliente" minLength="0" name="ac_0465081987f1f9f3ebc976a4db1e6c0388aa26998d" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/clientes/get" style="" type="text" uppercase="true" value="" valueclear="true" valuefield="id_cliente"></input><em class="autocomplete_search  autosuggest"></em></span></p>
                    </td>
                    <td>
                        <p class="field " style="width:auto; "><span class="input " rel="cpf_cnpj_cliente" style=""><input disabled="disabled" id="cpf_cnpj_cliente" name="cpf_cnpj_cliente" style="" type="text" value=""></input></span></p>
                    </td>
                </tr>

                </tbody>
            </table>

        </fieldset>
    </div>
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
</div>