<div class="tab" id="tab_dashboard_439952405e5325a0ccac32f4cc1477917abee21b7" ref="Opções" rel="tab_dashboard">
    <fieldset class="fieldset " show="inline" style="width:960px;">
        <legend><span class="legend">
                <span class="legend_label">Opções da Tela Inicial</span>
                <span class="input_info" style="">
                    <img alt="info" class="infotip" src="/images/info.png" title="Indica as informações que o funcionário terá acesso na página inicial do sistema"></img>
                </span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="checkbox_field  block" style="">
            <label class="" for="visualizar_dashboard" style="">
                <input id="visualizar_dashboard" name="visualizar_dashboard" rel="0" style="" type="checkbox" value="1"></input>
                <span>Permitir visualizar Painel de Informações (Dashboard)</span>
            </label>
        </p>
        <p class="checkbox_field  block" style="">
            <label class="" for="visualizar_todos_funcionarios" style="">
                <input id="visualizar_todos_funcionarios" name="visualizar_todos_funcionarios" rel="0" style="" type="checkbox" value="1"></input>
                <span>Permitir visualizar informações de todos os funcionários na Dashboard</span>
            </label>
        </p>


    </fieldset>

    <!-- (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR  -->
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>
        &nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
    <!-- FIM (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR -->

</div>