<div class="tab" id="tab_enderecos" ref="Endereços" rel="tab_enderecos">

    <fieldset class="fieldset " style="width:97%;">

        <legend>
            <span class="legend">
                <span class="legend_label">Endereço</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>

        <div id="endereco">
            <input class="clone_flag" name="endereco_flag" type="hidden" value=""></input>
            <!-- ENDEREÇO 1-->
            <div class="clonedField" id="endereco0">

                <input class="clone_id" id="endereco_entidade__id_0" name="endereco_entidade__id[0]" type="hidden" value=""></input>
                <input class="clone_readonly" id="endereco_readonly_0" name="endereco_readonly[0]" type="hidden" value="{readonly}">
                <input id="endereco_principal_0" name="endereco_principal[0]" type="hidden" value=""></input>
                <input id="endereco__id_0" name="endereco__id[0]" type="hidden" value=""></input>
                <input id="endereco_entidade__principal_0" name="endereco_entidade__principal[0]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_entidade_0" name="endereco_entidade__id_entidade[0]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_endereco_0" name="endereco_entidade__id_endereco[0]" type="hidden" value=""></input>
                <input class="disabled" disabled="disabled" id="endereco__logradouro_0" name="endereco__logradouro[0]" requiredCep="true" size="38%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_nome" name="cidade_nome" size="19%" type="hidden" value=""></input>
                <input id="estado_nome" name="estado_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="pais_nome" name="pais_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_cod" name="cidade_cod" size="18%" type="hidden" value=""></input>
                <input id="estado_cod" name="estado_cod" size="18%" type="hidden" value=""></input>
                <input id="pais_cod" name="pais_cod" size="18%" type="hidden" value=""></input>
                <input id="endereco__id_pais" name="endereco__id_pais" type="hidden" value=""></input>

                <div style="position:absolute; top:0px; width: 100%; background-color: #FFF; height: 24px; ">

                    <p class="field " style="width:auto; ">
                        <span class="input radio" rel="" style="">
                            <label class="inline">
                                <input class="" eval="" name="principal_radio[]" style="" type="radio" value="1"></input>
                                <span>Principal</span>
                            </label>
                        </span>
                    </p>

                </div>

                <div style="position:relative; margin-top: 30px;">

                    <!-- CEP -->
                    <p class="field " style="width:90px; ">
                        <label class="" for="endereco__cep_0" style="">Cep</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__cep_0" style="">
                            <input class=" required" id="endereco__cep_0" mask="99999-999" name="endereco__cep[0]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_cep" name="Buscar CEP" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar CEP"></input>

                    <!-- Logradouro -->
                    <p class="field " style="width:448px; ">
                        <label class="" for="endereco__logradouro_0" style="">Logradouro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__logradouro_0" style="">
                            <input class=" required" id="endereco__logradouro_0" name="endereco__logradouro[0]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_correio" name="Buscar" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar"></input>

                    <!-- Numero -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__numero_0" style="">Número</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__numero_0" style="">
                            <input class=" required" id="endereco_entidade__numero_0" maxlength="5" name="endereco_entidade__numero[0]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Complemento -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__complemento_0" style="">Complemento</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__complemento_0" style="">
                            <input id="endereco_entidade__complemento_0" maxlength="20" name="endereco_entidade__complemento[0]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <hr class="clear" size="1"></hr>

                    <!-- Bairro -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__bairro_0" style="">Bairro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__bairro_0" style="">
                            <input class=" required" id="endereco__bairro_0" name="endereco__bairro[0]" style="" type="text" uppercase="true" value="">
                            </input>
                        </span>
                    </p>

                    <!-- Cidade -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__id_cidade_0" style="">Cidade</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__id_cidade_0" style="">
                            <input id="endereco__id_cidade_0" name="endereco__id_cidade[0]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco__id_cidade[0]" class=" required autosuggest" filters="[]" form_title="Cadastrando Cidade" form_url="" form_url_field="" id="endereco__id_cidade_0" minLength="0" name="ac_0" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/enderecos/ac_cidade" style="" type="text" uppercase="true" value="{cidade}" valueclear="true" valuefield="id_cidade"></input>
                            <em class="autocomplete_search  required autosuggest"></em>
                        </span>
                    </p>

                    <!-- Referencia -->
                    <p class="field " style="width:18%; ">
                        <label class="" for="endereco_entidade__informacoes_adicionais_0" style="">Referência</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__informacoes_adicionais_0" style="">
                            <input id="endereco_entidade__informacoes_adicionais_0" name="endereco_entidade__informacoes_adicionais[0]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Tipo de endereco -->
                    <p class="field " style="width:131px; ">
                        <label class="" for="endereco_entidade__id_tipo_cadastro_0" style="">Tipo de Endereço</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__id_tipo_cadastro_0" style="">
                            <input id="endereco_entidade__id_tipo_cadastro_0" name="endereco_entidade__id_tipo_cadastro[0]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco_entidade__id_tipo_cadastro[0]" class=" autosuggest" filters="[]" form_title="Cadastrando Tipo de Endereço" form_url="http://app.tagplus.com.br/empresariamkk/cadastro/tipos_cadastros/form" form_url_field="descricao" id="endereco_entidade__id_tipo_cadastro_19697571984b991d73040c0773fed931347b17e7340" minLength="0" name="ac_0173976576419f809e9e7d3e3222165a18df2828a5b" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/tipos_cadastros/get" style="" type="text" value="" valueclear="true" valuefield="id"></input>
                            <em class="autocomplete_search  autosuggest"></em>
                        </span>
                    </p>

                    <!-- Estado -->
                    <p class="field " style="width:38px; ">
                        <label class="" for="estado" style="">Estado</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="estado" style="">
                            <input class="disabled" disabled="disabled" id="estado" name="estado" style="" type="text" uppercase="true" value="{estado}"></input>
                        </span>
                    </p>

                    <input class="btn_mapa" count="0" disabled="disabled" id="btn_mapa" name="btn_mapa" style="float:left;margin-top:13px; margin-left:1%" type="button" value="Mapa"></input>

                </div>
            </div>
            <!-- FIM ENDEREÇO  -->

            <!-- ENDEREÇO 2 -->
            <div class="clonedField" id="endereco1">

                <input class="clone_id" id="endereco_entidade__id_1" name="endereco_entidade__id[1]" type="hidden" value=""></input>
                <input class="clone_readonly" id="endereco_readonly_1" name="endereco_readonly[1]" type="hidden" value="{readonly}">
                <input id="endereco_principal_1" name="endereco_principal[1]" type="hidden" value=""></input>
                <input id="endereco__id_1" name="endereco__id[1]" type="hidden" value=""></input>
                <input id="endereco_entidade__principal_1" name="endereco_entidade__principal[1]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_entidade_1" name="endereco_entidade__id_entidade[1]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_endereco_1" name="endereco_entidade__id_endereco[1]" type="hidden" value=""></input>
                <input class="disabled" disabled="disabled" id="endereco__logradouro_1" name="endereco__logradouro[1]" requiredCep="true" size="38%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_nome" name="cidade_nome" size="19%" type="hidden" value=""></input>
                <input id="estado_nome" name="estado_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="pais_nome" name="pais_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_cod" name="cidade_cod" size="18%" type="hidden" value=""></input>
                <input id="estado_cod" name="estado_cod" size="18%" type="hidden" value=""></input>
                <input id="pais_cod" name="pais_cod" size="18%" type="hidden" value=""></input>
                <input id="endereco__id_pais" name="endereco__id_pais" type="hidden" value=""></input>

                <div style="position:absolute; top:0px; width: 100%; background-color: #FFF; height: 24px; ">

                    <p class="field " style="width:auto; ">
                        <span class="input radio" rel="" style="">
                            <label class="inline">
                                <input class="" eval="" name="principal_radio[]" style="" type="radio" value="1"></input>
                                <span>Principal</span>
                            </label>
                        </span>
                    </p>

                </div>

                <div style="position:relative; margin-top: 30px;">

                    <!-- CEP -->
                    <p class="field " style="width:90px; ">
                        <label class="" for="endereco__cep_1" style="">Cep</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__cep_1" style="">
                            <input class=" required" id="endereco__cep_1" mask="99999-999" name="endereco__cep[1]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_cep" name="Buscar CEP" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar CEP"></input>

                    <!-- Logradouro -->
                    <p class="field " style="width:448px; ">
                        <label class="" for="endereco__logradouro_1" style="">Logradouro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__logradouro_1" style="">
                            <input class=" required" id="endereco__logradouro_1" name="endereco__logradouro[1]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_correio" name="Buscar" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar"></input>

                    <!-- Numero -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__numero_1" style="">Número</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__numero_1" style="">
                            <input class=" required" id="endereco_entidade__numero_1" maxlength="5" name="endereco_entidade__numero[1]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Complemento -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__complemento_1" style="">Complemento</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__complemento_1" style="">
                            <input id="endereco_entidade__complemento_1" maxlength="20" name="endereco_entidade__complemento[1]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <hr class="clear" size="1"></hr>

                    <!-- Bairro -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__bairro_1" style="">Bairro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__bairro_1" style="">
                            <input class=" required" id="endereco__bairro_1" name="endereco__bairro[1]" style="" type="text" uppercase="true" value="">
                            </input>
                        </span>
                    </p>

                    <!-- Cidade -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__id_cidade_1" style="">Cidade</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__id_cidade_1" style="">
                            <input id="endereco__id_cidade_1" name="endereco__id_cidade[1]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco__id_cidade[1]" class=" required autosuggest" filters="[]" form_title="Cadastrando Cidade" form_url="" form_url_field="" id="endereco__id_cidade_1" minLength="0" name="ac_1" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/enderecos/ac_cidade" style="" type="text" uppercase="true" value="{cidade}" valueclear="true" valuefield="id_cidade"></input>
                            <em class="autocomplete_search  required autosuggest"></em>
                        </span>
                    </p>

                    <!-- Referencia -->
                    <p class="field " style="width:18%; ">
                        <label class="" for="endereco_entidade__informacoes_adicionais_1" style="">Referência</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__informacoes_adicionais_1" style="">
                            <input id="endereco_entidade__informacoes_adicionais_1" name="endereco_entidade__informacoes_adicionais[1]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Tipo de endereco -->
                    <p class="field " style="width:131px; ">
                        <label class="" for="endereco_entidade__id_tipo_cadastro_1" style="">Tipo de Endereço</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__id_tipo_cadastro_1" style="">
                            <input id="endereco_entidade__id_tipo_cadastro_1" name="endereco_entidade__id_tipo_cadastro[1]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco_entidade__id_tipo_cadastro[1]" class=" autosuggest" filters="[]" form_title="Cadastrando Tipo de Endereço" form_url="http://app.tagplus.com.br/empresariamkk/cadastro/tipos_cadastros/form" form_url_field="descricao" id="endereco_entidade__id_tipo_cadastro_19697571984b991d73040c0773fed931347b17e7340" minLength="0" name="ac_1173976576419f809e9e7d3e3222165a18df2828a5b" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/tipos_cadastros/get" style="" type="text" value="" valueclear="true" valuefield="id"></input>
                            <em class="autocomplete_search  autosuggest"></em>
                        </span>
                    </p>

                    <!-- Estado -->
                    <p class="field " style="width:38px; ">
                        <label class="" for="estado" style="">Estado</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="estado" style="">
                            <input class="disabled" disabled="disabled" id="estado" name="estado" style="" type="text" uppercase="true" value="{estado}"></input>
                        </span>
                    </p>

                    <input class="btn_mapa" count="0" disabled="disabled" id="btn_mapa" name="btn_mapa" style="float:left;margin-top:13px; margin-left:1%" type="button" value="Mapa"></input>

                </div>
            </div>
            <!-- FIM ENDEREÇO  -->

            <!-- ENDEREÇO 3 -->
            <div class="clonedField" id="endereco2">

                <input class="clone_id" id="endereco_entidade__id_2" name="endereco_entidade__id[2]" type="hidden" value=""></input>
                <input class="clone_readonly" id="endereco_readonly_2" name="endereco_readonly[2]" type="hidden" value="{readonly}">
                <input id="endereco_principal_2" name="endereco_principal[2]" type="hidden" value=""></input>
                <input id="endereco__id_2" name="endereco__id[2]" type="hidden" value=""></input>
                <input id="endereco_entidade__principal_2" name="endereco_entidade__principal[2]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_entidade_2" name="endereco_entidade__id_entidade[2]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_endereco_2" name="endereco_entidade__id_endereco[2]" type="hidden" value=""></input>
                <input class="disabled" disabled="disabled" id="endereco__logradouro_2" name="endereco__logradouro[2]" requiredCep="true" size="38%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_nome" name="cidade_nome" size="19%" type="hidden" value=""></input>
                <input id="estado_nome" name="estado_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="pais_nome" name="pais_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_cod" name="cidade_cod" size="18%" type="hidden" value=""></input>
                <input id="estado_cod" name="estado_cod" size="18%" type="hidden" value=""></input>
                <input id="pais_cod" name="pais_cod" size="18%" type="hidden" value=""></input>
                <input id="endereco__id_pais" name="endereco__id_pais" type="hidden" value=""></input>

                <div style="position:absolute; top:0px; width: 100%; background-color: #FFF; height: 24px; ">

                    <p class="field " style="width:auto; ">
                        <span class="input radio" rel="" style="">
                            <label class="inline">
                                <input class="" eval="" name="principal_radio[]" style="" type="radio" value="1"></input>
                                <span>Principal</span>
                            </label>
                        </span>
                    </p>

                </div>

                <div style="position:relative; margin-top: 30px;">

                    <!-- CEP -->
                    <p class="field " style="width:90px; ">
                        <label class="" for="endereco__cep_2" style="">Cep</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__cep_2" style="">
                            <input class=" required" id="endereco__cep_2" mask="99999-999" name="endereco__cep[2]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_cep" name="Buscar CEP" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar CEP"></input>

                    <!-- Logradouro -->
                    <p class="field " style="width:448px; ">
                        <label class="" for="endereco__logradouro_2" style="">Logradouro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__logradouro_2" style="">
                            <input class=" required" id="endereco__logradouro_2" name="endereco__logradouro[2]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_correio" name="Buscar" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar"></input>

                    <!-- Numero -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__numero_2" style="">Número</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__numero_2" style="">
                            <input class=" required" id="endereco_entidade__numero_2" maxlength="5" name="endereco_entidade__numero[2]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Complemento -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__complemento_2" style="">Complemento</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__complemento_2" style="">
                            <input id="endereco_entidade__complemento_2" maxlength="20" name="endereco_entidade__complemento[2]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <hr class="clear" size="1"></hr>

                    <!-- Bairro -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__bairro_2" style="">Bairro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__bairro_2" style="">
                            <input class=" required" id="endereco__bairro_2" name="endereco__bairro[2]" style="" type="text" uppercase="true" value="">
                            </input>
                        </span>
                    </p>

                    <!-- Cidade -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__id_cidade_2" style="">Cidade</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__id_cidade_2" style="">
                            <input id="endereco__id_cidade_2" name="endereco__id_cidade[2]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco__id_cidade[2]" class=" required autosuggest" filters="[]" form_title="Cadastrando Cidade" form_url="" form_url_field="" id="endereco__id_cidade_2" minLength="0" name="ac_2" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/enderecos/ac_cidade" style="" type="text" uppercase="true" value="{cidade}" valueclear="true" valuefield="id_cidade"></input>
                            <em class="autocomplete_search  required autosuggest"></em>
                        </span>
                    </p>

                    <!-- Referencia -->
                    <p class="field " style="width:18%; ">
                        <label class="" for="endereco_entidade__informacoes_adicionais_2" style="">Referência</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__informacoes_adicionais_2" style="">
                            <input id="endereco_entidade__informacoes_adicionais_2" name="endereco_entidade__informacoes_adicionais[2]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Tipo de endereco -->
                    <p class="field " style="width:131px; ">
                        <label class="" for="endereco_entidade__id_tipo_cadastro_2" style="">Tipo de Endereço</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__id_tipo_cadastro_2" style="">
                            <input id="endereco_entidade__id_tipo_cadastro_2" name="endereco_entidade__id_tipo_cadastro[2]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco_entidade__id_tipo_cadastro[2]" class=" autosuggest" filters="[]" form_title="Cadastrando Tipo de Endereço" form_url="http://app.tagplus.com.br/empresariamkk/cadastro/tipos_cadastros/form" form_url_field="descricao" id="endereco_entidade__id_tipo_cadastro_29697571984b991d73040c0773fed931347b17e7340" minLength="0" name="ac_2173976576419f809e9e7d3e3222165a18df2828a5b" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/tipos_cadastros/get" style="" type="text" value="" valueclear="true" valuefield="id"></input>
                            <em class="autocomplete_search  autosuggest"></em>
                        </span>
                    </p>

                    <!-- Estado -->
                    <p class="field " style="width:38px; ">
                        <label class="" for="estado" style="">Estado</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="estado" style="">
                            <input class="disabled" disabled="disabled" id="estado" name="estado" style="" type="text" uppercase="true" value="{estado}"></input>
                        </span>
                    </p>

                    <input class="btn_mapa" count="0" disabled="disabled" id="btn_mapa" name="btn_mapa" style="float:left;margin-top:13px; margin-left:1%" type="button" value="Mapa"></input>

                </div>
            </div>
            <!-- FIM ENDEREÇO  -->

            <!-- ENDEREÇO 4 -->
            <div class="clonedField" id="endereco3">

                <input class="clone_id" id="endereco_entidade__id_3" name="endereco_entidade__id[3]" type="hidden" value=""></input>
                <input class="clone_readonly" id="endereco_readonly_3" name="endereco_readonly[3]" type="hidden" value="{readonly}">
                <input id="endereco_principal_3" name="endereco_principal[3]" type="hidden" value=""></input>
                <input id="endereco__id_3" name="endereco__id[3]" type="hidden" value=""></input>
                <input id="endereco_entidade__principal_3" name="endereco_entidade__principal[3]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_entidade_3" name="endereco_entidade__id_entidade[3]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_endereco_3" name="endereco_entidade__id_endereco[3]" type="hidden" value=""></input>
                <input class="disabled" disabled="disabled" id="endereco__logradouro_3" name="endereco__logradouro[3]" requiredCep="true" size="38%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_nome" name="cidade_nome" size="19%" type="hidden" value=""></input>
                <input id="estado_nome" name="estado_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="pais_nome" name="pais_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_cod" name="cidade_cod" size="18%" type="hidden" value=""></input>
                <input id="estado_cod" name="estado_cod" size="18%" type="hidden" value=""></input>
                <input id="pais_cod" name="pais_cod" size="18%" type="hidden" value=""></input>
                <input id="endereco__id_pais" name="endereco__id_pais" type="hidden" value=""></input>

                <div style="position:absolute; top:0px; width: 100%; background-color: #FFF; height: 24px; ">

                    <p class="field " style="width:auto; ">
                        <span class="input radio" rel="" style="">
                            <label class="inline">
                                <input class="" eval="" name="principal_radio[]" style="" type="radio" value="1"></input>
                                <span>Principal</span>
                            </label>
                        </span>
                    </p>

                </div>

                <div style="position:relative; margin-top: 30px;">

                    <!-- CEP -->
                    <p class="field " style="width:90px; ">
                        <label class="" for="endereco__cep_3" style="">Cep</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__cep_3" style="">
                            <input class=" required" id="endereco__cep_3" mask="99999-999" name="endereco__cep[3]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_cep" name="Buscar CEP" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar CEP"></input>

                    <!-- Logradouro -->
                    <p class="field " style="width:448px; ">
                        <label class="" for="endereco__logradouro_3" style="">Logradouro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__logradouro_3" style="">
                            <input class=" required" id="endereco__logradouro_3" name="endereco__logradouro[3]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_correio" name="Buscar" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar"></input>

                    <!-- Numero -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__numero_3" style="">Número</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__numero_3" style="">
                            <input class=" required" id="endereco_entidade__numero_3" maxlength="5" name="endereco_entidade__numero[3]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Complemento -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__complemento_3" style="">Complemento</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__complemento_3" style="">
                            <input id="endereco_entidade__complemento_3" maxlength="20" name="endereco_entidade__complemento[3]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <hr class="clear" size="1"></hr>

                    <!-- Bairro -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__bairro_3" style="">Bairro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__bairro_3" style="">
                            <input class=" required" id="endereco__bairro_3" name="endereco__bairro[3]" style="" type="text" uppercase="true" value="">
                            </input>
                        </span>
                    </p>

                    <!-- Cidade -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__id_cidade_3" style="">Cidade</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__id_cidade_3" style="">
                            <input id="endereco__id_cidade_3" name="endereco__id_cidade[3]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco__id_cidade[3]" class=" required autosuggest" filters="[]" form_title="Cadastrando Cidade" form_url="" form_url_field="" id="endereco__id_cidade_3" minLength="0" name="ac_3" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/enderecos/ac_cidade" style="" type="text" uppercase="true" value="{cidade}" valueclear="true" valuefield="id_cidade"></input>
                            <em class="autocomplete_search  required autosuggest"></em>
                        </span>
                    </p>

                    <!-- Referencia -->
                    <p class="field " style="width:18%; ">
                        <label class="" for="endereco_entidade__informacoes_adicionais_3" style="">Referência</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__informacoes_adicionais_3" style="">
                            <input id="endereco_entidade__informacoes_adicionais_3" name="endereco_entidade__informacoes_adicionais[3]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Tipo de endereco -->
                    <p class="field " style="width:131px; ">
                        <label class="" for="endereco_entidade__id_tipo_cadastro_3" style="">Tipo de Endereço</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__id_tipo_cadastro_3" style="">
                            <input id="endereco_entidade__id_tipo_cadastro_3" name="endereco_entidade__id_tipo_cadastro[3]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco_entidade__id_tipo_cadastro[3]" class=" autosuggest" filters="[]" form_title="Cadastrando Tipo de Endereço" form_url="http://app.tagplus.com.br/empresariamkk/cadastro/tipos_cadastros/form" form_url_field="descricao" id="endereco_entidade__id_tipo_cadastro_39697571984b991d73040c0773fed931347b17e7340" minLength="0" name="ac_3173976576419f809e9e7d3e3222165a18df2828a5b" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/tipos_cadastros/get" style="" type="text" value="" valueclear="true" valuefield="id"></input>
                            <em class="autocomplete_search  autosuggest"></em>
                        </span>
                    </p>

                    <!-- Estado -->
                    <p class="field " style="width:38px; ">
                        <label class="" for="estado" style="">Estado</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="estado" style="">
                            <input class="disabled" disabled="disabled" id="estado" name="estado" style="" type="text" uppercase="true" value="{estado}"></input>
                        </span>
                    </p>

                    <input class="btn_mapa" count="0" disabled="disabled" id="btn_mapa" name="btn_mapa" style="float:left;margin-top:13px; margin-left:1%" type="button" value="Mapa"></input>

                </div>
            </div>
            <!-- FIM ENDEREÇO  -->

            <!-- ENDEREÇO 5 -->
            <div class="clonedField" id="endereco4">

                <input class="clone_id" id="endereco_entidade__id_4" name="endereco_entidade__id[4]" type="hidden" value=""></input>
                <input class="clone_readonly" id="endereco_readonly_4" name="endereco_readonly[4]" type="hidden" value="{readonly}">
                <input id="endereco_principal_4" name="endereco_principal[4]" type="hidden" value=""></input>
                <input id="endereco__id_4" name="endereco__id[4]" type="hidden" value=""></input>
                <input id="endereco_entidade__principal_4" name="endereco_entidade__principal[4]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_entidade_4" name="endereco_entidade__id_entidade[4]" type="hidden" value=""></input>
                <input id="endereco_entidade__id_endereco_4" name="endereco_entidade__id_endereco[4]" type="hidden" value=""></input>
                <input class="disabled" disabled="disabled" id="endereco__logradouro_4" name="endereco__logradouro[4]" requiredCep="true" size="38%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_nome" name="cidade_nome" size="19%" type="hidden" value=""></input>
                <input id="estado_nome" name="estado_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="pais_nome" name="pais_nome" size="19%" type="hidden" uppercase="true" value=""></input>
                <input id="cidade_cod" name="cidade_cod" size="18%" type="hidden" value=""></input>
                <input id="estado_cod" name="estado_cod" size="18%" type="hidden" value=""></input>
                <input id="pais_cod" name="pais_cod" size="18%" type="hidden" value=""></input>
                <input id="endereco__id_pais" name="endereco__id_pais" type="hidden" value=""></input>

                <div style="position:absolute; top:0px; width: 100%; background-color: #FFF; height: 24px; ">

                    <p class="field " style="width:auto; ">
                        <span class="input radio" rel="" style="">
                            <label class="inline">
                                <input class="" eval="" name="principal_radio[]" style="" type="radio" value="1"></input>
                                <span>Principal</span>
                            </label>
                        </span>
                    </p>

                </div>

                <div style="position:relative; margin-top: 30px;">

                    <!-- CEP -->
                    <p class="field " style="width:90px; ">
                        <label class="" for="endereco__cep_4" style="">Cep</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__cep_4" style="">
                            <input class=" required" id="endereco__cep_4" mask="99999-999" name="endereco__cep[4]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_cep" name="Buscar CEP" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar CEP"></input>

                    <!-- Logradouro -->
                    <p class="field " style="width:448px; ">
                        <label class="" for="endereco__logradouro_4" style="">Logradouro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__logradouro_4" style="">
                            <input class=" required" id="endereco__logradouro_4" name="endereco__logradouro[4]" style="" type="text" uppercase="true" value=""></input>
                        </span>
                    </p>

                    <input class="btn_view" id="btn_correio" name="Buscar" size="50px" style="margin-left:5px;margin-top:16px;height:30px;float:left" type="button" value="Buscar"></input>

                    <!-- Numero -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__numero_4" style="">Número</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__numero_4" style="">
                            <input class=" required" id="endereco_entidade__numero_4" maxlength="5" name="endereco_entidade__numero[4]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Complemento -->
                    <p class="field " style="width:8%; ">
                        <label class="" for="endereco_entidade__complemento_4" style="">Complemento</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__complemento_4" style="">
                            <input id="endereco_entidade__complemento_4" maxlength="20" name="endereco_entidade__complemento[4]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <hr class="clear" size="1"></hr>

                    <!-- Bairro -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__bairro_4" style="">Bairro</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__bairro_4" style="">
                            <input class=" required" id="endereco__bairro_4" name="endereco__bairro[4]" style="" type="text" uppercase="true" value="">
                            </input>
                        </span>
                    </p>

                    <!-- Cidade -->
                    <p class="field " style="width:25%; ">
                        <label class="" for="endereco__id_cidade_4" style="">Cidade</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco__id_cidade_4" style="">
                            <input id="endereco__id_cidade_4" name="endereco__id_cidade[4]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco__id_cidade[4]" class=" required autosuggest" filters="[]" form_title="Cadastrando Cidade" form_url="" form_url_field="" id="endereco__id_cidade_4" minLength="0" name="ac_4" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/enderecos/ac_cidade" style="" type="text" uppercase="true" value="{cidade}" valueclear="true" valuefield="id_cidade"></input>
                            <em class="autocomplete_search  required autosuggest"></em>
                        </span>
                    </p>

                    <!-- Referencia -->
                    <p class="field " style="width:18%; ">
                        <label class="" for="endereco_entidade__informacoes_adicionais_4" style="">Referência</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__informacoes_adicionais_4" style="">
                            <input id="endereco_entidade__informacoes_adicionais_4" name="endereco_entidade__informacoes_adicionais[4]" style="" type="text" value=""></input>
                        </span>
                    </p>

                    <!-- Tipo de endereco -->
                    <p class="field " style="width:131px; ">
                        <label class="" for="endereco_entidade__id_tipo_cadastro_4" style="">Tipo de Endereço</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="endereco_entidade__id_tipo_cadastro_4" style="">
                            <input id="endereco_entidade__id_tipo_cadastro_4" name="endereco_entidade__id_tipo_cadastro[4]" type="hidden" value=""></input>
                            <i class="ui-autocomplete_combo" tabindex="-1"></i>
                            <input autosuggest="endereco_entidade__id_tipo_cadastro[4]" class=" autosuggest" filters="[]" form_title="Cadastrando Tipo de Endereço" form_url="http://app.tagplus.com.br/empresariamkk/cadastro/tipos_cadastros/form" form_url_field="descricao" id="endereco_entidade__id_tipo_cadastro_49697571984b991d73040c0773fed931347b17e7340" minLength="0" name="ac_4173976576419f809e9e7d3e3222165a18df2828a5b" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/empresariamkk/autocomplete/tipos_cadastros/get" style="" type="text" value="" valueclear="true" valuefield="id"></input>
                            <em class="autocomplete_search  autosuggest"></em>
                        </span>
                    </p>

                    <!-- Estado -->
                    <p class="field " style="width:38px; ">
                        <label class="" for="estado" style="">Estado</label>
                        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="estado" style="">
                            <input class="disabled" disabled="disabled" id="estado" name="estado" style="" type="text" uppercase="true" value="{estado}"></input>
                        </span>
                    </p>

                    <input class="btn_mapa" count="0" disabled="disabled" id="btn_mapa" name="btn_mapa" style="float:left;margin-top:13px; margin-left:1%" type="button" value="Mapa"></input>

                </div>
            </div>
            <!-- FIM ENDEREÇO  -->
            <input class="cloneable" rel="endereco" separator="true" type="button" value="Inserir Endereço"></input>

        </div>

    </fieldset>

    <!-- (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR  -->
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>
        &nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
    <!-- FIM (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR -->

</div>


