<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv='cache-control' content='no-cache'/>
    <meta http-equiv='expires' content='0'/>
    <meta http-equiv='pragma' content='no-cache'/>
    <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    <meta name="base_url" content=""/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <!-- Script da pagina js/code -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/mootools-1.2-core.js')
        ->appendFile($this->basePath() . '/js/mootools-1.2-more.js')
        ->appendFile($this->basePath() . '/js/core.js')
        ->appendFile($this->basePath() . '/js/window.js')
        ->appendFile($this->basePath() . '/js/modal.js')
        ->appendFile($this->basePath() . '/js/mocha-ext.js')
        ->appendFile($this->basePath() . '/js/base.js')
        ->appendFile($this->basePath() . '/js/atalhos.js')
        ->appendFile($this->basePath() . '/js/detect-zoom.js')
        ->appendFile($this->basePath() . '/js/jquery/core.js')
        ->appendFile($this->basePath() . '/js/jquery/dump.js')
        ->appendFile($this->basePath() . '/js/jquery/debug.js')
        ->appendFile($this->basePath() . '/js/jquery/bt.js')
        ->appendFile($this->basePath() . '/js/jquery/validate.js')
        ->appendFile($this->basePath() . '/js/jquery/maskedinput.js')
        ->appendFile($this->basePath() . '/js/jquery/uppercase.js')
        ->appendFile($this->basePath() . '/js/jquery/clonefield.js')
        ->appendFile($this->basePath() . '/js/jquery/priceformat.js')
        ->appendFile($this->basePath() . '/js/jquery/tab.js')
        ->appendFile($this->basePath() . '/js/jquery/tablestyle.js')
        ->appendFile($this->basePath() . '/js/jquery/date.js')
        ->appendFile($this->basePath() . '/js/jquery/datepicker.js')
        ->appendFile($this->basePath() . '/js/jquery/readonly.js')
        ->appendFile($this->basePath() . '/js/sexyalertbox.js')
        ->appendFile($this->basePath() . '/js/jquery/confirm_message.js')
        ->appendFile($this->basePath() . '/js/jquery/livequery.js')
        ->appendFile($this->basePath() . '/js/forms.js')
        ->appendFile($this->basePath() . '/js/jquery/barcode.js')
        ->appendFile($this->basePath() . '/js/jquery/ui.js')
        ->appendFile($this->basePath() . '/js/jquery/autosuggest.js')
        ->appendFile($this->basePath() . '/js/jquery/clonetable.js')
        ->appendFile($this->basePath() . '/js/jquery/radioImageSelect.js')
        ->appendFile($this->basePath() . '/js/script_criar_venda_form.js')
        ->appendFile($this->basePath() . '/js/moostarrating.js') ?>

    <!-- Estilos da pagina Css/code -->
    <?php echo $this->headLink()
        //->appendStylesheet($this->basePath() . '/css/noprint.css')
        ->appendStylesheet($this->basePath() . '/css/glyphs.css')
        ->appendStylesheet($this->basePath() . '/css/loader.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/style_tagplus.css')
        ->appendStylesheet($this->basePath() . '/css/sexyalertbox.css')
        ->appendStylesheet($this->basePath() . '/css/datepicker.css')
        ->appendStylesheet($this->basePath() . '/css/jqueryui.css')
        ->appendStylesheet($this->basePath() . '/css/clonetable.css')
        ->appendStylesheet($this->basePath() . '/css/style_clientes_form.css') ?>
</head>

<body>
<!--Container tela.php-->
<div id="loader">
    <div class="loader-text">
        <span class='carregando'>Carregando ...</span>
        <span class='enviando' style="display: none">Enviando ...</span>
    </div>
    <div class="loader-bg">&nbsp;</div>
</div>

<div id="tela" style="height: 100%;">

    <div id="conteudo">

        <?php
        $form->setAttribute('action',$this->url('clientes-listar/default',array('controller'=>'clientes','action'=>'save')));
        $form->setAttribute('windowId',$this->url('clientes-listar/default',array('controller'=>'clientes','action'=>'form')));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <!-- BOTOES DO FORM -->
        <?php echo $this->partial('partials/form_botoes_clientes'); ?>
        <!-- -->
        <div class="form_fields" id="form_fields">

            <!-- TAB DADOS PESSOAIS -->
            <?php echo $this->partial('partials/tab_configuracao_1'); ?>
            <!-- -->

            <!-- TAB DADOS SECUNDARIOS -->
            <?php //echo $this->partial('partials/tab_dados_secundarios_clientes'); ?>
            <!-- -->

            <!-- TAB DE CONTATOS -->
            <?php //echo $this->partial('partials/tab_contatos_clientes'); ?>
            <!-- -->

            <!-- TAB ENDERECO -->
            <?php //echo $this->partial('partials/tab_enderecos_clientes'); ?>
            <!-- -->

            <!-- TAB TRIBUTACAO -->
            <?php //echo $this->partial('partials/tab_tributacao_clientes'); ?>
            <!-- -->

            <!-- TAB NOTAS VINCULADAS -->
            <?php //echo $this->partial('partials/tab_notas_vinculadas_clientes'); ?>
            <!-- -->

            <!-- TAB SALDO CLIENTES -->
            <?php //echo $this->partial('partials/tab_saldo_clientes'); ?>
            <!-- -->

            <!-- TAB VENDEDORES CLIENTES -->
            <?php //echo $this->partial('partials/tab_vendedores_clientes'); ?>
            <!-- -->

        </div>
        <?php echo $this->form()->closeTag();?>
    </div>
</div>

<div id="footer"></div>
</body>
</html>