 <div class="tab tab_fixed" id="label_aba_fornecedores_1704556609091d2320906062532922bcdca19ede44" ref="Fornecedores" rel="label_aba_fornecedores">
                        <div class="fieldset" style="width: 98%">
                            <fieldset class="fieldset " style="width: 97%;">
                                <legend>
                                    <span class="legend"><span class="legend_label">Fornecedores</span><span class="input_alert">&nbsp;</span></span>
                                </legend>

                                <table borborder="0" cellpadding="0" cellspacing="0" class="form_table" id="produto_fornecedores" style="width: 98%">
                                    <thead>
                                        <tr>
                                            <th width="64%">Fornecedor</th>
                                            <th width="33%">CPF/CNPJ</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <tr>
                                            <td>
                                               
                                               
                                               <?php echo $this->formElement($form->get('produto_fornecedor__id'));?>
                                               <?php echo $this->formElement($form->get('produto_fornecedor__id_produto'));?>
                                                
                                                <p class="field " style="width: auto;">
                                                    <span class="input " rel="produto_fornecedor__id_fornecedor" style="">
                                                    
                                                    <?php echo $this->formElement($form->get('produto_fornecedor__id_fornecedor'));?>
														
														
														<i class="ui-autocomplete_combo"
														tabindex="-1"></i>
														
														
														<?php echo $this->formElement($form->get('ac_01871149116349e3b5e4b5d1abf0ea5a865a0f6f596'));?>
														
														
														<em
														class="autocomplete_search  autosuggest"></em></span>
                                                </p>
                                            </td>
                                            <td>
                                                <p class="field " style="width: auto;">
                                                    <span class="input " rel="cpf_cnpj_fornecedor" style="">
                                                    
                                                   <?php echo $this->formElement($form->get('cpf_cnpj_fornecedor'));?>
														
														
														</span>
                                                </p>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>

                            </fieldset>
                        </div>
                        <div class="tab_navigator ">
                            <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
                            <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
                        </div>
                    </div>