   <div class="tab tab_fixed" id="label_loja_virtual_119025756977215a526b1193775f64b1092674b614" ref="Loja Virtual" rel="label_loja_virtual">

                        <div class="help_infos" id="fieldset_loja_virtual" style="">
                            <div style="">Aqui você define as características do produto que serão exibidas na Loja Virtual, caso este produto seja marcado para sincronização.</div>
                        </div>

                        <div class="fieldset" style="padding: 10px 10px; margin: 2px 4px 4px; width: 97%; background-color: #FEF5DC; border: 1px solid #F3EAD1;">
                            <p class="checkbox_field  block" style="">
                                <label class="" for="produto_ecommerce__sincroniza" style="">
                                    <input id="produto_ecommerce__sincroniza" name="produto_ecommerce__sincroniza" rel="" style="" type="checkbox" value="1"></input><span>Sincronizar este
										produto com a Loja Virtual</span>
                                </label>
                            </p>
                        </div>

                        <div id="loja_infos" style="width: 97%">

                            <div class="fieldset" style="width: 44%; float: left; margin: 0 9px 0 2px;">
                                <fieldset class="fieldset " style="width: 97%;">

                                    <p class="checkbox_field  block" style="margin: 8px 3px 0; padding: 10px 0 8px; border-top: 1px solid #E5E5E5; width: 98%;">
                                        <label class="" for="produto_ecommerce__ignore_manage_stock" style="">
                                            <input id="produto_ecommerce__ignore_manage_stock" name="produto_ecommerce__ignore_manage_stock" rel="" style="" type="checkbox" value="1"></input><span>Ignorar situação do
												estoque deste produto</span>
                                        </label><span class="input_info"><img alt="info"
											class="infotip"
											src="/images/info.png"
											title="Permite realizar a venda deste produto na Loja Virtual ignorando quantidade em estoque."></img></span>
                                    </p>

                                </fieldset>

                                <fieldset class="fieldset " style="width: 97%; padding-top: 10px; padding-bottom: 10px;">
                                    <legend>
                                        <span class="legend"><span class="legend_label">Exibir como
												Oferta</span><span class="input_info"><img alt="info"
												class="infotip"
												src="/images/info.png"
												title="Valor e Período em que o produto será exibido como 'OFERTA' na loja virtual"></img></span><span class="input_alert">&nbsp;</span></span>
                                    </legend>

                                    <div style="border-bottom: 1px solid #E5E5E5; margin-bottom: 9px; float: left; width: 100%; padding-bottom: 8px;">
                                        <p class="field " style="width: auto;">
                                            <label class="" for="valor_venda_varejo" style="margin-top: 7px;">Valor de Venda (Varejo)</label>
                                            <span class="input_alert">&nbsp;</span><span class="input " rel="valor_venda_varejo" style="width: 132px;">
                                            
                                            <?php echo $this->formElement($form->get('valor_venda_varejo'));?>
                                            </span>
                                        </p>
                                        <p class="field " style="width: auto; margin-left: 20px">
                                            <label class="" for="produto_ecommerce__special_price" style="width: 126px; margin-top: 7px;">Valor Oferta</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto_ecommerce__special_price" style="width: 132px;"><input
												id="produto_ecommerce__special_price"
												name="produto_ecommerce__special_price"
												number_format="+#.#0,[2,2]"
												style="font-size: 22px; height: auto; padding: 3px;"
												type="text" value=""></input></span>
                                        </p>

                                    </div>
                                    <div style="float: left; width: 150px; margin-top: 8px;">
                                        <p class="field inline" style="width: auto;">
                                            <label class="" for="produto_ecommerce__sale_from_date" style="width: 30px;">De</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto_ecommerce__sale_from_date" style="width: 112px;"><input class=" date"
												id="produto_ecommerce__sale_from_date" mask="39/19/9999"
												name="produto_ecommerce__sale_from_date" style=""
												type="text" value=""></input></span>
                                        </p>
                                    </div>
                                    <div style="float: left; width: 150px; margin-top: 8px;">
                                        <p class="field inline" style="width: auto;">
                                            <label class="" for="produto_ecommerce__sale_to_date" style="width: 20px; margin-right: 10px;">até</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto_ecommerce__sale_to_date" style="width: 112px;"><input
												class=" date" id="produto_ecommerce__sale_to_date"
												mask="39/19/9999" name="produto_ecommerce__sale_to_date"
												style="" type="text" value=""></input></span>
                                        </p>
                                    </div>
                                    <input class="btn_limpar" id="limpar_loja_oferta" name="Limpar" style="margin-left: 5px;" type="button" value="Limpar"></input>

                                </fieldset>

                            </div>

                            <fieldset class="fieldset " style="width: 51%; margin: 0;">
                                <legend>
                                    <span class="legend"><span class="legend_label">Informações
											para Sincronização</span><span class="input_alert">&nbsp;</span></span>
                                </legend>

                                <p class="field " style="width: auto;">
                                    <label class="" for="produto_ecommerce__short_description" style="">Descrição Resumida</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto_ecommerce__short_description" style=""><textarea cols="90"
											id="produto_ecommerce__short_description"
											name="produto_ecommerce__short_description" rows="12"
											style="height: 50px;" width="490"></textarea></span>
                                </p>
                                <p class="field " style="width: auto;">
                                    <label class="" for="produto_ecommerce__long_description" style="">Descrição Detalhada</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto_ecommerce__long_description" style=""><textarea cols="90"
											id="produto_ecommerce__long_description"
											name="produto_ecommerce__long_description" rows="12"
											style="height: 130px;" width="490"></textarea></span>
                                </p>

                            </fieldset>
                        </div>
                        <div class="tab_navigator ">
                            <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
                            <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
                        </div>
                    </div>