            <div class="tab tab_fixed  " id="label_produto_valores_4934751624477aaa33573a7112e1d4af8e9adf050" ref="Valores & Custos" rel="label_produto_valores">
                        <div class="help_infos" id="tip_cabecalho" style="">
                            <div style="">

                                <ol>
                                    Para entender por completo a funcionalidade de Valores, Custos e Lucratividade do sistema,
                                    <a href='https://www.gattecnologia.com.br/?wpdmact=process&did=NzUuaG90bGluaw=='>Clique
										aqui. </a>
                                </ol>
                            </div>
                        </div>
                        <fieldset class="fieldset " style="width: 28%; float: left;">
                            <legend>
                                <span class="legend"><span class="legend_label">Custos</span><span class="input_info"><img alt="info" class="infotip"
										src="/images/info.png"
										title="Os valores de custos serão alterados baseado no custo dos produtos que compõe o mesmo."></img></span><span class="input_alert">&nbsp;</span></span>
                            </legend>

                            <p class="field inline" style="width: auto;">
                                <label class="" for="custo_medio" style="width: 40%;">Custo Médio
                                </label><span class="input_info"><img alt="info"
									class="infotip"
									src="/images/info.png"
									title="Indica o Custo Médio das compras realizadas, calculado de acordo com Opções do Sistema. Caso seja Composição ou Kit os valores considerados serão dos produtos agregados"></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="custo_medio" style="width: 40%;"><input class="disabled"
									disabled="disabled" id="custo_medio" name="custo_medio"
									number_format="+#.#0,[2,2]" style="" type="text" value="0.01"></input></span>
                            </p>
                            <input id="custo_medio_hidden" name="custo_medio_hidden" type="hidden" value=""></input>
                            <p class="field inline" style="width: auto;">
                                <label class="" for="despesas_acessorias" style="width: 40%;">Despesas Acessórias
                                </label><span class="input_info"><img alt="info"
									class="infotip"
									src="/images/info.png"
									title="Indica o Custo Médio do Frete, Seguro e Despesas Acessórias das compras realizadas, calculado de acordo com Opções do Sistema. Caso seja Composição ou Kit os valores considerados serão dos produtos agregados"></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="despesas_acessorias" style="width: 40%;"><input
									class="disabled" disabled="disabled" id="despesas_acessorias"
									name="despesas_acessorias" number_format="+#.#0,[2,2]" style=""
									type="text" value="0.01"></input></span>
                            </p>
                            <p class="field inline" style="width: auto;">
                                <label class="" for="produto__custo_outras_despesas" style="width: 40%;">Outras Despesas</label><span class="input_info"><img alt="info" class="infotip"
									src="/images/info.png"
									title="Campo livre para indicação de demais despesas"></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="produto__custo_outras_despesas" style="width: 40%;"><input
									id="produto__custo_outras_despesas"
									name="produto__custo_outras_despesas"
									number_format="+#.#0,[2,2]" style="" type="text" value=""></input></span>
                            </p>
                            <p class="field inline" style="width: auto;">
                                <label class="" for="produto__custo_utilizado" style="width: 40%;">Valor de Custo</label><span class="input_info"><img alt="info" class="infotip"
									src="/images/info.png"
									title="Somatório do Custo Médio, Despesas Acessórias e Outras Despesas"></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="produto__custo_utilizado" style="width: 40%;"><input
									class=" positive" id="produto__custo_utilizado"
									name="produto__custo_utilizado" number_format="+#.#0,[2,2]"
									style="" type="text" value="0,01"></input></span>
                            </p>
                            <input class="btn_calculator" id="btn_calcular_vr_custo" name="Calcular Valor de Custo" style="margin-top: 3px; margin-left: 91px; float: left" type="button" value="Calcular Valor de Custo"></input>

                        </fieldset>

                        <fieldset class="fieldset " style="width: 68%;">
                            <legend>
                                <span class="legend"><span class="legend_label">Valor de Venda</span><span class="input_alert">&nbsp;</span></span>
                            </legend>

                            <input id="json_impostos_comissoes" name="json_impostos_comissoes" type="hidden" value=""></input>
                            <input class="load" id="btn_impostos_comissoes" name="Informar Impostos e Comissões" type="button" value="Informar Impostos e Comissões"></input>
                            <input class="btn_suggest" id="btn_suggest" name="Calcular Valor de Venda" type="button" value="Calcular Valor de Venda"></input>
                            <table border="0" cellpadding="0" cellspacing="0" class="form_table" id="table_vl_vendas">
                                <thead>
                                    <tr>
                                        <th width="35%">Tipo</th>
                                        <th width="15%">% Lucro Sugerido</th>
                                        <th width="15%">% Lucro Utilizado</th>
                                        <th width="15%">Valor de Venda Sugerido</th>
                                        <th width="15%">Valor de Venda</th>
                                    </tr>
                                </thead>

                                <tbody>

                                    <tr>
                                        <td><span>A prazo</span>
                                            <input name="produto_valor_venda__id[]" ref="pvv_id" type="hidden" value=""></input>
                                            <input name="produto_valor_venda__id_produto[]" type="hidden" value=""></input>
                                            <input id="tipo_6" name="produto_valor_venda__id_produto_tabela_tipo_valor[]" ref="produto_valor_venda__id_produto_tabela_tipo_valor" type="hidden" value="6"></input>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="pvv_valor_lucro_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="pvv_valor_lucro_sugerido"
													name="pvv_valor_lucro_sugerido" number_format="+#.#0,[2,2]"
													ref="pvv_valor_lucro_sugerido" style="" type="text"
													value="60"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a" style=""><input
													id="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a"
													name="produto_valor_venda__lucro_utilizado[]"
													number_format="+#.#0,[2,2]"
													ref="produto_valor_venda__lucro_utilizado" style=""
													type="text" value="0.01"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="valor_venda_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="valor_venda_sugerido" name="valor_venda_sugerido"
													number_format="+#.#0,[2,2]" ref="valor_venda_sugerido"
													style="" type="text" value=""></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__vr_venda_11569603222bdc7616727be4fdfab1e4e5c820d3f8" style="">
	                                               <?php echo $this->formElement($form->get('produto_valor_venda__vr_venda'));?>
													</input>
												</span>
                                            </p>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td><span>Atacado</span>
                                            <input name="produto_valor_venda__id[]" ref="pvv_id" type="hidden" value=""></input>
                                            <input name="produto_valor_venda__id_produto[]" type="hidden" value=""></input>
                                            <input id="tipo_4" name="produto_valor_venda__id_produto_tabela_tipo_valor[]" ref="produto_valor_venda__id_produto_tabela_tipo_valor" type="hidden" value="4"></input>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="pvv_valor_lucro_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="pvv_valor_lucro_sugerido"
													name="pvv_valor_lucro_sugerido" number_format="+#.#0,[2,2]"
													ref="pvv_valor_lucro_sugerido" style="" type="text"
													value="60"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a" style=""><input
													id="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a"
													name="produto_valor_venda__lucro_utilizado[]"
													number_format="+#.#0,[2,2]"
													ref="produto_valor_venda__lucro_utilizado" style=""
													type="text" value="0.01"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="valor_venda_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="valor_venda_sugerido" name="valor_venda_sugerido"
													number_format="+#.#0,[2,2]" ref="valor_venda_sugerido"
													style="" type="text" value=""></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__vr_venda_11569603222bdc7616727be4fdfab1e4e5c820d3f8" style="">
	                                                <?php echo $this->formElement($form->get('produto_valor_venda__vr_venda'));?>
													</input>
												</span>
                                            </p>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td><span>Interno</span>
                                            <input name="produto_valor_venda__id[]" ref="pvv_id" type="hidden" value=""></input>
                                            <input name="produto_valor_venda__id_produto[]" type="hidden" value=""></input>
                                            <input id="tipo_2" name="produto_valor_venda__id_produto_tabela_tipo_valor[]" ref="produto_valor_venda__id_produto_tabela_tipo_valor" type="hidden" value="2"></input>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="pvv_valor_lucro_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="pvv_valor_lucro_sugerido"
													name="pvv_valor_lucro_sugerido" number_format="+#.#0,[2,2]"
													ref="pvv_valor_lucro_sugerido" style="" type="text"
													value="15"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a" style=""><input
													id="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a"
													name="produto_valor_venda__lucro_utilizado[]"
													number_format="+#.#0,[2,2]"
													ref="produto_valor_venda__lucro_utilizado" style=""
													type="text" value="0.01"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="valor_venda_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="valor_venda_sugerido" name="valor_venda_sugerido"
													number_format="+#.#0,[2,2]" ref="valor_venda_sugerido"
													style="" type="text" value=""></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__vr_venda_11569603222bdc7616727be4fdfab1e4e5c820d3f8" style="">
	                                                <?php echo $this->formElement($form->get('produto_valor_venda__vr_venda'));?>
													</input>
												</span>
                                            </p>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td><span>Varejo</span>
                                            <input name="produto_valor_venda__id[]" ref="pvv_id" type="hidden" value=""></input>
                                            <input name="produto_valor_venda__id_produto[]" type="hidden" value=""></input>
                                            <input id="tipo_1" name="produto_valor_venda__id_produto_tabela_tipo_valor[]" ref="produto_valor_venda__id_produto_tabela_tipo_valor" type="hidden" value="1"></input>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="pvv_valor_lucro_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="pvv_valor_lucro_sugerido"
													name="pvv_valor_lucro_sugerido" number_format="+#.#0,[2,2]"
													ref="pvv_valor_lucro_sugerido" style="" type="text"
													value="30"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a" style=""><input
													id="produto_valor_venda__lucro_utilizado_80943960822a0c25e5b9e3d731be4108ab6bbc3a"
													name="produto_valor_venda__lucro_utilizado[]"
													number_format="+#.#0,[2,2]"
													ref="produto_valor_venda__lucro_utilizado" style=""
													type="text" value="0.01"></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="valor_venda_sugerido" style=""><input
													class="disabled" disabled="disabled"
													id="valor_venda_sugerido" name="valor_venda_sugerido"
													number_format="+#.#0,[2,2]" ref="valor_venda_sugerido"
													style="" type="text" value=""></input></span>
                                            </p>
                                        </td>
                                        <td>
                                            <p class="field " style="width: auto;">
                                                <span class="input " rel="produto_valor_venda__vr_venda_11569603222bdc7616727be4fdfab1e4e5c820d3f8" style="">
	                                                <?php echo $this->formElement($form->get('produto_valor_venda__vr_venda'));?>
													</input>
												</span>
                                            </p>
                                        </td>
                                    </tr>

                                </tbody>

                                <tfoot></tfoot>
                            </table>
                            <input class="cloneable" id="btn_novo_vr_venda" name="Cadastrar Novo Valor de Venda" style="float: right;" type="button" value="Cadastrar Novo Valor de Venda"></input>

                        </fieldset>
                        <hr class="clear" size="1"></hr>

                        <div class="tab_navigator ">
                            <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
                            <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
                        </div>
                    </div>