   <div class="tab tab_fixed" id="label_aba_notas_fiscais_688221528db02e739a15aec5edc09fb8eef442b83" ref="Movimentações" rel="label_aba_notas_fiscais">
                        <div id="div_notas_vinculadas" style="float: left; height: 92%; margin: 12px" width="100%">
                            <fieldset class="fieldset " style="width: 97%;" width="100%">

                                <table borborder="0" cellpadding="0" cellspacing="0" class="form_table lista" id="notas_pedidos" style="margin-top: 10px" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="15%">Tipo</th>
                                            <th width="10%">Número</th>
                                            <th width="10%">Série</th>
                                            <th width="10%">Valor Total</th>
                                            <th width="10%">Data Criação</th>
                                            <th width="10%">Data Confirmação</th>
                                            <th width="20%">Status</th>
                                            <th width="5%">Acessar</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <tr>
                                            <td class="left">
                                                <input name="entrada_saida" type="hidden" value=""></input>
                                                <input name="id_nf_vinculada" type="hidden" value="{id_nota}"></input>
                                                <input name="modelo_nf" type="hidden" value="{modelo_bd}"></input>
                                                {modelo}</td>
                                            <td class="right">{numero_nota}</td>
                                            <td class="right">{serie}</td>
                                            <td class="right">{vr_total_notas}</td>
                                            <td class="center">{data_criacao}</td>
                                            <td class="center">{data_confirmacao}</td>
                                            <td class="left">{situacao}</td>
                                            <td>
                                                <input class="button_in" name="Vizualizar Nota" ref="btn_acessar_nf_vinculada" type="button" value=""></input>
                                            </td>
                                        </tr>
                                        {/notas_vinculadas}
                                    </tbody>
                                </table>

                            </fieldset>
                        </div>
                        <div class="tab_navigator ">
                            <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
                            <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
                        </div>
                    </div>