<div class="tab tab_fixed" id="label_aba_atributos_4234042505d34c01f41768a9f2ccfd90344c62ae4" ref="Detalhes" rel="label_aba_atributos">
	<div style="float: left; width: 335px">
		<fieldset class="fieldset " style="width: 314px;">
			<legend>
				<span class="legend"><span class="legend_label">Pesos e
				dimensões</span><span class="input_info"><img alt="info" class="infotip"
					src="/images/info.png"
					title="Aqui você pode dar mais detalhes sobre o item.Este campos não são obrigatórios mas ajudam a ter uma maior riqueza de detalhes sobre cada item"></img></span><span class="input_alert">&nbsp;</span></span>
			</legend>
			<p class="field inline" style="width: auto;">
				<label class="" for="produto__peso" style="">Peso (Kg)</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__peso" style="">
				
				<?php echo $this->formElement($form->get('produto__peso'));?>
					
					
					
					</span>
			</p>
			<p class="field inline" style="width: auto;">
				<label class="" for="produto__largura" style="">Largura (mtr)</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__largura" style="">
				
				
			<?php echo $this->formElement($form->get('produto__largura'));?>
					
					
					</span>
			</p>
			<p class="field inline" style="width: auto;">
				<label class="" for="produto__altura" style="">Altura (mtr)</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__altura" style="">
				
			<?php echo $this->formElement($form->get('produto__altura'));?>	
					
					
					</span>
			</p>
			<p class="field inline" style="width: auto;">
				<label class="" for="produto__comprimento" style="">Comprimento (mtr)
				</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__comprimento" style="">
				
				<?php echo $this->formElement($form->get('produto__comprimento'));?>	
					
					</span>
			</p>
		</fieldset>
		<fieldset class="fieldset " style="width: 97%; width: 314px;">
			<legend>
				<span class="legend"><span class="legend_label">Detalhes</span><span class="input_alert">&nbsp;</span></span>
			</legend>
			<p class="field " style="width: auto; width: 130px">
				<label class="" for="produto__comissao" style="">Comissão (%)</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__comissao" style="">
				
				<?php echo $this->formElement($form->get('produto__comissao'));?>	
					
					
					
					</span>
			</p>
			<p class="field " style="width: auto; width: 130px">
				<label class="" for="produto__pontos" style="">Pontos</label><span class="input_alert">&nbsp;</span><span class="input " rel="produto__pontos" style="">
				
				
				<?php echo $this->formElement($form->get('produto__pontos'));?>
					
					
					</span>
			</p>
			
			
			<?php echo $this->formElement($form->get('vinculacao'));?>
			
			
			
			<div style="margin-left: 10px; margin-bottom: 10px;">
				<p class="checkbox_field info-top block" style="">
					<label class="" for="produto__serie" style="">
					
			<?php echo $this->formElement($form->get('produto__serie'));?>
					
					
					<span>Garantia</span>
					</label><span class="input_info"><img alt="info"
						class="infotip"
						src="/images/info.png"
						title="Indica se o item possui garantia.Informa o vendedor na hora da venda."></img></span>
				</p>
				<p class="checkbox_field info-top block" style="">
					<label class="" for="produto__vendido_separado" style="">
					
					
					<?php echo $this->formElement($form->get('produto__vendido_separado'));?>
					
					
					
					<span>Venda avulsa</span>
					</label><span class="input_info"><img alt="info"
						class="infotip"
						src="/images/info.png"
						title="Indica se o item poderá ser vendido separadamente ou somente caso ele pertençaa a uma Composição. Caso esteja desmarcado, este produto não poderá ser vendido em separado, mas somente vinculado à outros produtos."></img></span>
				</p>
				<p class="checkbox_field info-top block" style="display:none">
					<label class="" for="produto__comercializavel" style="">
					<input id="produto__comercializavel" name="produto__comercializavel" rel="1" style="" type="checkbox" value="1"></input><span>Comercializável
					no PDV</span>
					</label><span class="input_info"><img alt="info"
						class="infotip"
						src="/images/info.png"
						title="Indica que este produto poderá ser comercializado diretamente no PDV. Caso esteja desmarcado, não será permitido comercializá-lo diretamente no Ponto de Venda."></img></span>
				</p>
			</div>
		</fieldset>
		<fieldset class="fieldset " style="width: 97%; width: 314px;">
			<legend>
				<span class="legend"><span class="legend_label">Observações do
				item</span><span class="input_alert">&nbsp;</span></span>
			</legend>
			<p class="field " style="width: auto;">
				<span class="input " rel="produto__informacao_adicional" style="">
				
				<?php echo $this->formElement($form->get('produto__informacao_adicional'));?>
				
			</p>
		</fieldset>
		<fieldset class="fieldset " style="width: 97%;display:none!important	; width: 314px;">
			<legend>
				<span class="legend"><span class="legend_label">Informações de
				Produção</span><span class="input_alert">&nbsp;</span></span>
			</legend>
			<!--		<f:radio property='produto__tipo_producao' options="Propria_Terceira" validate="required"/>-->
			<p class="field " style="width: auto; width: 95px;">
				<label class="" for="produto__tipo_producao" style="">Tipo de Produção
				</label><span class="input_alert">&nbsp;</span>
				<span class="input " rel="produto__tipo_producao" style="">
					<select
						eval="T" id="produto__tipo_producao"
						name="produto__tipo_producao" size="1" style="">
						<option
							value="">Selecione</option>
						<option value="P">Própria</option>
						<option value="T">Terceiros</option>
					</select>
				</span>
			</p>
			<p class="field " style="width: auto;">
				<label class="" for="produto__cnpj_produtor" style="">CNPJ do Produtor
				</label><span class="input_info"><img alt="info"
					class="infotip"
					src="/images/info.png"
					title="Informações necessária somente para produtos para exportação."></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="produto__cnpj_produtor" style="">
					
					<input class=" cnpj"
					id="produto__cnpj_produtor" mask="99.999.999/9999-99"
					maxlength="20" name="produto__cnpj_produtor" style=""
					type="text" value=""></input></span>
			</p>
			<p class="field " style="width: auto;">
				<label class="" for="produto__ex_tipi" style="">EX TIPI</label><span class="input_info"><img alt="info" class="infotip"
					src="/images/info.png"
					title="Código de Exceção de NCM,de acordo com a Tabela de Incidência do Imposto de Produtos Industrializados (TIPI)."></img></span><span class="input_alert">&nbsp;</span><span class="input " rel="produto__ex_tipi" style="">
					
					
					<input id="produto__ex_tipi"
					maxlength="3" name="produto__ex_tipi" style="width: 30px;"
					type="text" value=""></input></span>
			</p>
		</fieldset>
	</div>
	<fieldset class="fieldset " style="width: 64%;">
		<legend>
			<span class="legend"><span class="legend_label">Atributos</span><span class="input_info"><img alt="info" class="infotip"
				src="/images/info.png"
				title="Indique a descrição do atributo e seu conteudo.<br/>
				Ex: Marca=> SILKSCREEN"></img></span><span class="input_alert">&nbsp;</span></span>
		</legend>
		<table borborder="0" cellpadding="0" cellspacing="0" class="form_table" id="produto_atributos" style="width: 98%">
			<thead>
				<tr>
					<th>Descrição</th>
					<th>Conteudo</th>
				</tr>
			</thead>
			<tbody>
		
		<!-- Loop para linhas de descricao -->
		<?php 
		if($this->atributos != null){
			foreach ($this->atributos AS $key => $value):
		?>
		<tr>
			<td>
				<input 
				name="produto_atributo__id" 
				id="produto_atributo__id" 
				type="hidden" 
				value=<?= $value['id']?>>						
			
				<input 
				name="produto_atributo__id_produto" 
				id="produto_atributo__id_produto" 
				type="hidden" 
				value=<?= $value['item']?>>						
				
				<p class="field " style="width: auto;">
					<span class="input " rel="produto_atributo__nome_atributo" style="">
						<input 
						name="produto_atributo__nome_atributo" 
						id="produto_atributo__nome_atributo" 
						type="text" 
						style="text-transform&#x3A;&#x20;uppercase" 
						class="primeiroCaractere" 
						uppercase="true" 
						value=<?= $value['nome']?>>								
					</span>
				</p>
			</td>

			<td>
				<p class="field " style="width: auto;">
					<span class="input " rel="produto_atributo__valor_atributo" style="">
						<input 
						name="produto_atributo__valor_atributo" 
						id="produto_atributo__valor_atributo" 
						type="text" 
						style="text-transform&#x3A;&#x20;uppercase" 
						value=<?= $value['valor']?>>								
					</span>
				</p>
			</td>
		</tr>		
		
		<?php 
		endforeach;
		}
		else
		{
		?>
						<tr>
					<td>
						
						<?php echo $this->formElement($form->get('produto_atributo__id'));?>
						<?php echo $this->formElement($form->get('produto_atributo__id_produto'));?>
						
						<p class="field " style="width: auto;">
							<span class="input " rel="produto_atributo__nome_atributo" style="">
							
							
							<?php echo $this->formElement($form->get('produto_atributo__nome_atributo'));?>
								
								
								
								</span>
						</p>
					</td>
					<td>
						<p class="field " style="width: auto;">
							<span class="input " rel="produto_atributo__valor_atributo" style="">
							
							
							<?php echo $this->formElement($form->get('produto_atributo__valor_atributo'));?>
								
								
								</span>
						</p>
					</td>
				</tr>
		
		
		<?php } ?>
		

		<!-- Fim Loop para linhas de descricao -->	
			</tbody>
		</table>
	</fieldset>
	<div class="tab_navigator ">
		<input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
		<input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
	</div>
</div>