<?php
/*
 * MODELO DE JSON DE RETORNO
 *{"page":1,
 *"total":"15",
 *"data":[
 *{
 *"id":"2",
 *"id_modalidade":null,
 *"descricao":"Cor",
 *"tipo":"M",
 *"modalidade":null
 *}
 *{"id":"8",
 *"id_modalidade":"2",
 *"descricao":"Amarelo",
 *"tipo":"G",
 *"modalidade":"Cor"},
 *]}
 */
$rows = array("page"=>(int)$this->page,'total'=>'', 'data'=>array()); 
foreach ( $this->data as $key => $entity ) :
	foreach ( $entity as $k => $e ) :
		$row [$k] = $e;
	endforeach;
	array_push ( $rows['data'], $row );
endforeach;
	$rows['total']="".$this->registos."";

print json_encode($rows);
