<html>
<head>
	<title>Erro :: _Senna</title>
	<!-- Estilos da pagina Css/code -->
	<?php echo $this->headLink()
		//->appendStylesheet($this->basePath() . '/css/noprint.css')
		->appendStylesheet($this->basePath() . '/css/error.css')
		->appendStylesheet($this->basePath() . '/css/error_tagplus.css')
	?>
</head>
<body>
<div id="content">
	<div id="logo">&nbsp;</div>
	<h1>Desculpe box fechado.</h1>
	<p>Não e possivel lhe fornecer acesso a esta pagina ou módulo.Talvez você não tenha acesso ou ele tenha sido revogado.Verifique com o administrador do sistema e tente novamente mais tarde.</p>	</div>
</body>
</html>