
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Senna::Login</title>
	
<?php echo $this->headScript ()
				->appendFile ( $this->basePath () . '/login/js/jquery-1.11.1.min.js' )
				->appendFile ( $this->basePath () . '/login/js/jquery-ui.min.js' )
?>
	    

<?php echo $this->headLink ()
				->appendStylesheet ( $this->basePath () . '/login/css/ass.css' )
?>
	
<?php echo $this->headLink ()
				->appendStylesheet ( $this->basePath () . '/login/css/bootstrap.css' )
?>

    <!-- Custom styles for this template -->
<?php echo $this->headLink ()
				->appendStylesheet ( $this->basePath () . '/login/css/style.css' )
?>    



  </head>

  <body class="login">
	 <form name="form1" action="/senna" method="post"> 
	<div id="login">
	
		<div class="logo">
			<a href="/"><img src="/images/senna_login.png" alt="" /></a>
		</div>
		
		<div class="wrapper-login">
			<input type="text" placeholder="Login" class="user" id="login"/>
			<input type="password"placeholder="Senha" class="password" id="senha"/>
		</div>
		
		<a href="/senna" class="login-button" id="entrar">Entrar</a>
		<span style="color:#FFFFFF">Esqueceu sua senha ?<a href="#">Redefinir</a></span>
	</div>
	</form>
	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

<?php echo $this->headScript ()
				->appendFile ( $this->basePath () . '/login/js/prettycheckable.js' )
				->appendFile ( $this->basePath () . '/login/js/tipsy.js' )
				->appendFile ( $this->basePath () . '/login/js/jquery.nestable.js' )
				->appendFile ( $this->basePath () . '/login/js/jquery.mousewheel.js' )
				->appendFile ( $this->basePath () . '/login/js/perfect-scrollbar.js' )
				->appendFile ( $this->basePath () . '/login/js/custom.js' )
				->appendFile ( $this->basePath () . '/login/js/bootstrap.min.js' )
?>
    

  </body>
  

<script language="javascript" type="text/javascript">
  
  $( document ).ready(function() {
		$( "#entrar" ).click(function() {

	

			if($('.user').val() == "admin" && $('.password').val() =="306325")
				{
				return true;
				}
			else
				{
				alert('Usuario ou senhas incorretos.')
				$('.user').val('');
				$('.user').val('');
				$('.user').focus();
				return false;
				}
 

			
			
			
			});
	  });
  </script>
</html>
