<?php
if(isset($this->data))
{
    echo $this->data;
}
elseif(isset($this->bloqueio))
{
    header("HTTP/1.0 500 Internal Server Error");

    echo "<h5>Atenção:</h5><br/><div style='max-height:270px;overflow:auto;display:block;'>O perfil selecionado não pode ser excluido.<br />Seu usuario está cadastrado com perfil que você está tentando excluir.</div>";
    die();
}
else
{
    header("HTTP/1.0 500 Internal Server Error");

    echo "<h5>Atenção:</h5><br/><div style='max-height:270px;overflow:auto;display:block;'>O perfil não pode ser excluido pois é o unico cadastrado.</div>";
    die();
}
