<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv='cache-control' content='no-cache'/>
    <meta http-equiv='expires' content='0'/>
    <meta http-equiv='pragma' content='no-cache'/>
    <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    <meta name="base_url" content=""/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>


    <!-- Scripts javaScript -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/mootools-1.2-core.js')
        ->appendFile($this->basePath() . '/js/mootools-1.2-more.js')
        ->appendFile($this->basePath() . '/js/core.js')
        ->appendFile($this->basePath() . '/js/Window.js')
        ->appendFile($this->basePath() . '/js/Modal.js')
        ->appendFile($this->basePath() . '/js/mocha-ext.js')
        ->appendFile($this->basePath() . '/js/base.js')
        ->appendFile($this->basePath() . '/js/atalhos.js')
        ->appendFile($this->basePath() . '/js/detect-zoom.js')
        ->appendFile($this->basePath() . '/js/jQuery/core.js')
        ->appendFile($this->basePath() . '/js/forms.js')
        ->appendFile($this->basePath() . '/js/jQuery/bt.js')
        ->appendFile($this->basePath() . '/js/listing.js')
        ->appendFile($this->basePath() . '/js/omnigrid.js')
        ->appendFile($this->basePath() . '/js/sexyalertbox.js')
        ->appendFile($this->basePath() . '/js/script_perfis_index.js') ?>


    <!-- Estilos da pagina Css/code -->
    <?php echo $this->headLink()
        //->appendStylesheet($this->basePath() . '/css/noprint.css')
        ->appendStylesheet($this->basePath() . '/css/loader.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/style_tagplus.css')
        ->appendStylesheet($this->basePath() . '/css/glyphs.css')
        ->appendStylesheet($this->basePath() . '/css/listing.css')
        ->appendStylesheet($this->basePath() . '/css/omnigrid.css')
        ->appendStylesheet($this->basePath() . '/css/sexyalertbox.css') ?>

</head>

<body>

<div id="loader">
    <div class="loader-text">
        <span class='carregando'>Carregando ...</span>
        <span class='enviando' style="display: none">Enviando ...</span>
    </div>
    <div class="loader-bg">&nbsp;</div>
</div>

<div id="tela" style="height: 100%;">
    <div id="conteudo">
        <div id="list_control">
            <form action="<?php echo $this->basePath() ?>/senna/usuario/perfis/filter" class="form" debug="false" enctype="text/plain" id="filter" method="post">
                <input name="add" type="button" value="Novo" windowName="Cadastro de Perfis de Acesso"></input>
                <input name="edit" type="button" value="Alterar"></input>
                <input confirm="Deseja realmente apagar o Perfil de Acesso selecionado?" debug="false" name="delete" type="button" value="Apagar"></input>
                <input debug="true" name="pesquisar" type="submit" value=""></input>
                <span><p class="field " style="width:auto; "><span class="input " rel="search_text" style=""><input class="focus" id="search_text" name="busca" placeholder="Filtrar" style="" type="text" value=""></input></span></p>
                </span>
            </form>
        </div>

        <div id="datatable" windowName="Alterar dados de Perfil de Acesso">
            <div col="id" hidden="true" type="number" width="5%">COD</div>
            <div col="nome" type="string">Perfil</div>
            <div col="admin" type="string">Privilegios de Administrador</div>
            <div col="criado" type="string" width="10%">Criado em</div>
            <div col="atualizado" type="string" width="10%">Atualizado em</div>
        </div>

        <div add_btn_title="Clique aqui para adicionar um novo registro" adv_search_btn_title="Limpe ou altere o Filtro Avançado para exibir resultados" id="list_empty" search_btn_title="Remova ou altere sua pesquisa para exibir resultados">
            <h3>Nenhum registro foi encontrado</h3>
        </div>

    </div>
</div>

<div id="footer"></div>

</body>
</html>