<div class="form_actions" id="form_actions">
    <input class="save" name="Salvar" saveWindowForm="true" type="submit" value="Salvar"></input>
    <input class="save_new" name="Salvar e Criar Novo" newWindowForm="true" type="submit" value="Salvar e Criar Novo"></input>
    <input class="save_close" closeWindow="true" name="Salvar e Fechar" type="submit" value="Salvar e Fechar"></input>
    <input class="delete" confirm="Tem certeza que deseja apagar este registro?" deleteUrl="http://app.tagplus.com.br/capitalponto/cadastro/clientes/delete/" disabled="disabled" labelsConfirm="{'labelSim':'Sim','labelNao':'Não'}" name="Apagar" type="button" value="Apagar"></input>
    <div class="action_menu_wrapper">
        <input class="action_menu_trigger noicon" style="" type="button" value="Mais Ações"></input>
        <span class="action_menu">
            <input class="document_properties" name="button_consulta_cnpj" type="button" value="Consultar CNPJ"></input>
            <a href="http://www.receita.fazenda.gov.br/aplicacoes/atcta/cpf/consultapublica.asp" style="text-decoration:none" target="_blank">
                <input class="btn_document_inspect" name="button_consulta_cpf" type="button" value="Consultar CPF"></input>
            </a>
            <input id="button_saldo_devedor" name="saldo_devedor" type="button" value="Saldo Devedor"></input>
        </span>
    </div>
    <span class="sep" size="1">&nbsp;</span>
    <input cancelForm="true" class="cancel" name="Fechar" type="button" value="Fechar"></input>
</div>