<div class="tab" id="tab_configuracao_1" ref="<img src='../../../images/data.png'> Tipo de item" rel="tab_configuracao_1">

    <form action="" method="post">
        <input id="example-1-1" type="radio" name="example-1" value="1" class="radioImageSelect" data-image="../../../images/venda/cracha.png" checked="checked" />
        <label for="example-1-1">Radio button 1</label>

        <input id="example-1-2" type="radio" name="example-1" value="2" class="radioImageSelect" data-image="../../../images/venda/layout_02.gif" />
        <label for="example-1-2">Radio button 2</label>

        <input id="example-1-3" type="radio" name="example-1" value="3" class="radioImageSelect" data-image="../../../images/venda/layout_03.gif" />
        <label for="example-1-3">Radio button 3</label>
    </form>
</div>