<div class="tab" id="tab_contatos" ref="<img src='../../../images/icon_contato.png'>  Contatos Extras" rel="tab_contatos">

    <fieldset class="fieldset " style="width:97%;">
        <legend>
            <span class="legend">
                <span class="legend_label">Contatos</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <div id="contato">

            <input class="clone_flag" name="contato_flag" type="hidden" value=""></input>

            <!-- CAMPOS DE CONTATO 1 -->
            <div class="clonedField hiddenClone" id="contato0">

                <?php echo $this->formElement($input = $form->get('contato__id[0]'));?>
                <?php echo $this->formElement($input = $form->get('contato__editavel[0]'));?>
                <?php echo $this->formElement($input = $form->get('contato__id_entidade[0]'));?>

                <p class="field " style="width:115px; ">
                    <label class="" for="contato__id_tipo_cadastro_0" style="">Tipo de Cadastro</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_cadastro_0" style="">
                         <?php echo $this->formElement($input = $form->get('contato__id_tipo_cadastro[0]'));?>
                    </span>
                </p>

                <p class="field " style="width:105px; ">
                    <label class="" for="contato__id_tipo_contato_0" style="">Tipo de Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_contato_0" style="">
                        <?php echo $this->formElement($input = $form->get('contato__id_tipo_contato[0]'));?>
                        <i class="ui-autocomplete_combo" tabindex="-1"></i>
                        <?php echo $this->formElement($input = $form->get('ac_0'));?>
                        <em class="autocomplete_search  required autosuggest"></em>
                    </span>
                </p>

                <p class="field " style="width:auto; width:270px">
                    <label class="" for="contato__descricao_0" style="">Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__descricao_0" style="">
                        <?php echo $this->formElement($input = $form->get('contato__descricao[0]'));?>
                    </span>
                </p>

                <p class="field " style="width:auto; width:310px">
                    <label class="" for="contato__detalhes_0" style="">Detalhes</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__detalhes_0" style="">
                        <?php echo $this->formElement($input = $form->get('contato__detalhes[0]'));?>
                    </span>
                </p>

                <hr class="clear" size="1"></hr>
            </div>
            <!-- FIM CAMPOS DE CONTATO 1 -->

            <!-- CAMPOS DE CONTATO 2 -->
            <div class="clonedField hiddenClone" id="contato1">

                <?php echo $this->formElement($input = $form->get('contato__id[1]'));?>
                <?php echo $this->formElement($input = $form->get('contato__editavel[1]'));?>
                <?php echo $this->formElement($input = $form->get('contato__id_entidade[1]'));?>

                <p class="field " style="width:115px; ">
                    <label class="" for="contato__id_tipo_cadastro_1" style="">Tipo de Cadastro</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_cadastro_1" style="">
                         <?php echo $this->formElement($input = $form->get('contato__id_tipo_cadastro[1]'));?>
                    </span>
                </p>

                <p class="field " style="width:105px; ">
                    <label class="" for="contato__id_tipo_contato_1" style="">Tipo de Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_contato_1" style="">
                        <?php echo $this->formElement($input = $form->get('contato__id_tipo_contato[1]'));?>
                        <i class="ui-autocomplete_combo" tabindex="-1"></i>
                        <?php echo $this->formElement($input = $form->get('ac_1'));?>
                        <em class="autocomplete_search  required autosuggest"></em>
                    </span>
                </p>

                <p class="field " style="width:auto; width:270px">
                    <label class="" for="contato__descricao_1" style="">Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__descricao_1" style="">
                        <?php echo $this->formElement($input = $form->get('contato__descricao[1]'));?>
                    </span>
                </p>

                <p class="field " style="width:auto; width:310px">
                    <label class="" for="contato__detalhes_1" style="">Detalhes</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__detalhes_1" style="">
                        <?php echo $this->formElement($input = $form->get('contato__detalhes[1]'));?>
                    </span>
                </p>

                <hr class="clear" size="1"></hr>
            </div>
            <!-- FIM CAMPOS DE CONTATO 2 -->

            <!-- CAMPOS DE CONTATO 3 -->
            <div class="clonedField hiddenClone" id="contato2">

                <?php echo $this->formElement($input = $form->get('contato__id[2]'));?>
                <?php echo $this->formElement($input = $form->get('contato__editavel[2]'));?>
                <?php echo $this->formElement($input = $form->get('contato__id_entidade[2]'));?>

                <p class="field " style="width:115px; ">
                    <label class="" for="contato__id_tipo_cadastro_2" style="">Tipo de Cadastro</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_cadastro_2" style="">
                         <?php echo $this->formElement($input = $form->get('contato__id_tipo_cadastro[2]'));?>
                    </span>
                </p>

                <p class="field " style="width:105px; ">
                    <label class="" for="contato__id_tipo_contato_2" style="">Tipo de Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_contato_2" style="">
                        <?php echo $this->formElement($input = $form->get('contato__id_tipo_contato[2]'));?>
                        <i class="ui-autocomplete_combo" tabindex="-1"></i>
                        <?php echo $this->formElement($input = $form->get('ac_2'));?>
                        <em class="autocomplete_search  required autosuggest"></em>
                    </span>
                </p>

                <p class="field " style="width:auto; width:270px">
                    <label class="" for="contato__descricao_2" style="">Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__descricao_2" style="">
                        <?php echo $this->formElement($input = $form->get('contato__descricao[2]'));?>
                    </span>
                </p>

                <p class="field " style="width:auto; width:310px">
                    <label class="" for="contato__detalhes_2" style="">Detalhes</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__detalhes_2" style="">
                        <?php echo $this->formElement($input = $form->get('contato__detalhes[2]'));?>
                    </span>
                </p>

                <hr class="clear" size="1"></hr>

            </div>
            <!-- FIM CAMPOS DE CONTATO 1 -->

            <!-- CAMPOS DE CONTATO 4 -->
            <div class="clonedField hiddenClone" id="contato3">

                <?php echo $this->formElement($input = $form->get('contato__id[3]'));?>
                <?php echo $this->formElement($input = $form->get('contato__editavel[3]'));?>
                <?php echo $this->formElement($input = $form->get('contato__id_entidade[3]'));?>

                <p class="field " style="width:115px; ">
                    <label class="" for="contato__id_tipo_cadastro_3" style="">Tipo de Cadastro</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_cadastro_3" style="">
                         <?php echo $this->formElement($input = $form->get('contato__id_tipo_cadastro[3]'));?>
                    </span>
                </p>

                <p class="field " style="width:105px; ">
                    <label class="" for="contato__id_tipo_contato_3" style="">Tipo de Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_contato_3" style="">
                        <?php echo $this->formElement($input = $form->get('contato__id_tipo_contato[3]'));?>
                        <i class="ui-autocomplete_combo" tabindex="-1"></i>
                        <?php echo $this->formElement($input = $form->get('ac_3'));?>
                        <em class="autocomplete_search  required autosuggest"></em>
                    </span>
                </p>

                <p class="field " style="width:auto; width:270px">
                    <label class="" for="contato__descricao_3" style="">Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__descricao_3" style="">
                        <?php echo $this->formElement($input = $form->get('contato__descricao[3]'));?>
                    </span>
                </p>

                <p class="field " style="width:auto; width:310px">
                    <label class="" for="contato__detalhes_3" style="">Detalhes</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__detalhes_3" style="">
                        <?php echo $this->formElement($input = $form->get('contato__detalhes[3]'));?>
                    </span>
                </p>

                <hr class="clear" size="1"></hr>

            </div>
            <!-- FIM CAMPOS DE CONTATO 4 -->

            <!-- CAMPOS DE CONTATO 5 -->
            <div class="clonedField hiddenClone" id="contato4">

                <?php echo $this->formElement($input = $form->get('contato__id[4]'));?>
                <?php echo $this->formElement($input = $form->get('contato__editavel[4]'));?>
                <?php echo $this->formElement($input = $form->get('contato__id_entidade[4]'));?>

                <p class="field " style="width:115px; ">
                    <label class="" for="contato__id_tipo_cadastro_4" style="">Tipo de Cadastro</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_cadastro_4" style="">
                         <?php echo $this->formElement($input = $form->get('contato__id_tipo_cadastro[4]'));?>
                    </span>
                </p>

                <p class="field " style="width:105px; ">
                    <label class="" for="contato__id_tipo_contato_4" style="">Tipo de Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__id_tipo_contato_4" style="">
                        <?php echo $this->formElement($input = $form->get('contato__id_tipo_contato[4]'));?>
                        <i class="ui-autocomplete_combo" tabindex="-1"></i>
                        <?php echo $this->formElement($input = $form->get('ac_4'));?>
                        <em class="autocomplete_search  required autosuggest"></em>
                    </span>
                </p>

                <p class="field " style="width:auto; width:270px">
                    <label class="" for="contato__descricao_4" style="">Contato</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__descricao_4" style="">
                        <?php echo $this->formElement($input = $form->get('contato__descricao[4]'));?>
                    </span>
                </p>

                <p class="field " style="width:auto; width:310px">
                    <label class="" for="contato__detalhes_4" style="">Detalhes</label>
                    <span class="input_alert">&nbsp;</span>
                    <span class="input " rel="contato__detalhes_4" style="">
                        <?php echo $this->formElement($input = $form->get('contato__detalhes[4]'));?>
                    </span>
                </p>

                <hr class="clear" size="1"></hr>

            </div>
            <!-- CAMPOS DE CONTATO 5 -->

            <input class="cloneable" rel="contato" separator="false" type="button" value="Inserir novo contato"></input>

        </div>

    </fieldset>

    <!-- (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR  -->
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>
        &nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
    <!-- FIM (LADO DIREITO) BOTÕES CONTINUAR-VOLTAR -->

</div>

