<div class="tab" id="label_vendedores_19553316285b159959fbbafb7e0a037ba023b71732" ref="Vendedores" rel="label_vendedores">
    <div class="help_infos" id="tip_cabecalho" style=" ">
        <div style=""> Caso deseje que o funcionário venda exclusivamente para determinado(s) cliente(s), basta inseri-lo(s) abaixo. Ao realizar uma venda, se o funcionário não tiver permissão, ela não será concretizada/finalizada. Opção válida para as seguintes movimentações: Pedido/Orçamento, Venda Simples, Pré-Venda, Dav, Dav OS, NF-e e NFS-e.</div>
    </div>
    <div class="fieldset" style="width:98%">
        <fieldset class="fieldset " style="width:97%;">
            <legend>
                <span class="legend"><span class="legend_label">Vendedores</span><span class="input_alert">&nbsp;</span></span>
            </legend>

            <table borborder="0" cellpadding="0" cellspacing="0" class="form_table" id="clientes_vendedores" style="width:98%">
                <thead>
                <tr>
                    <th width="53%">Vendedor</th>
                    <th width="22%">cpf/cnpj</th>
                    <th width="22%">data/hora</th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <td>
                        <input id="cliente_vendedor__id" name="cliente_vendedor__id" type="hidden" value=""></input>
                        <input id="cliente_vendedor__id_cliente" name="cliente_vendedor__id_cliente" type="hidden" value=""></input>

                        <p class="field " style="width:auto; ">
                            <span class="input " rel="cliente_vendedor__id_funcionario" style=""><input id="cliente_vendedor__id_funcionario" name="cliente_vendedor__id_funcionario" type="hidden" value=""></input><i class="ui-autocomplete_combo" tabindex="-1"></i><input autosuggest="cliente_vendedor__id_funcionario" class=" autosuggest" filters="[]" form_title="Cadastrando false" form_url="" form_url_field="" id="cliente_vendedor__id_funcionario" minLength="0" name="ac_075248590606e925f38f07a83545b0790eec2e2fe0" new_item_info="Criar um novo registro" new_item_label="Cadastrar Novo" source="http://app.tagplus.com.br/capitalponto/autocomplete/funcionarios/get_funcionario" style="" type="text" uppercase="true" value="" valueclear="true" valuefield="id_funcionario"></input><em class="autocomplete_search  autosuggest"></em></span>
                        </p>
                    </td>
                    <td>
                        <p class="field " style="width:auto; ">
                            <span class="input " rel="cpf_cnpj_vendedor" style=""><input disabled="disabled" id="cpf_cnpj_vendedor" name="cpf_cnpj_vendedor" style="text-align:center;" type="text" value=""></input></span>
                        </p>
                    </td>
                    <td>
                        <p class="field " style="width:auto; ">
                            <span class="input " rel="cliente_vendedor__data_hora" style=""><input disabled="disabled" id="cliente_vendedor__data_hora" name="cliente_vendedor__data_hora" style="text-align:center;" type="text" value=""></input></span>
                        </p>
                    </td>
                </tr>

                </tbody>
            </table>

        </fieldset>
    </div>
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
</div>