<div class="tab" id="tab_dados_secundarios_1650646463dd738473d0bcb0bbc3b29ca71af789d3" ref="Dados Secundarios" rel="tab_dados_secundarios">

    <fieldset class="fieldset " id="fisica" style="width:720px;float:left;">
        <legend>
                            <span class="legend"><span class="legend_label">Dados Secundarios</span>
                                <span class="input_alert">&nbsp;</span>
                            </span>
        </legend>

        <div>
            <p class="field " style="width:90px; ">
                <label class="" for="rg" style="">RG</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="rg" style="">
                                    <input id="rg" maxlength="45" name="rg" style="" type="text" value=""></input>
                                </span>
            </p>

            <p class="field " style="width:auto; ">
                <label class="" for="data_nascimento" style="">Data de Nascimento</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="data_nascimento" style="">
                                    <input class=" date" id="data_nascimento" mask="39/19/9999" name="data_nascimento" style="" type="text" value=""></input>
                                </span>
            </p>

            <p class="field " style="width:auto; ">
                <label class="" style="">Sexo</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input radio" rel="" style="">
                                    <label class="inline" style="">
                                        <input class="" eval="M" name="sexo" style="" type="radio" value="F"></input>
                                        <span style="">Feminino</span>
                                    </label>
                                    <label class="inline" style="">
                                        <input class="" eval="M" name="sexo" style="" type="radio" value="M"></input>
                                        <span style="">Masculino</span>
                                    </label>
                                </span>
            </p>

            <p class="field " style="width:120px; ">
                <label class="" for="estado_civil" style="">Estado Civil</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="estado_civil" style="">
                                    <select class="" eval="" id="estado_civil" name="estado_civil" size="1" style="">
                                        <option value="S">Solteiro</option>
                                        <option value="C">Casado</option>
                                        <option value="D">Divorciado</option>
                                        <option value="V">Viúvo</option>
                                    </select>
                                </span>
            </p>
            <p class="field " style="width:80px; ">
                <label class="" for="renda_mensal" style="">Renda Mensal</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="renda_mensal" style="">
                                    <input id="renda_mensal" name="renda_mensal" number_format="+#.#0,[2,2]" style="" type="text" value=""></input>
                                </span>
            </p>

            <hr class="clear" size="1"></hr>

            <p class="field " style="width:200px; ">
                <label class="" for="profissao" style="">Profissão</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="profissao" style="">
                                    <input id="profissao" maxlength="50" name="profissao" style="" type="text" value=""></input>
                                </span>
            </p>

            <p class="field " style="width:230px; ">
                <label class="" for="filiacao_mae" style="">Nome da Mãe</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="filiacao_mae" style="">
                                    <input id="filiacao_mae" maxlength="255" name="filiacao_mae" style="" type="text" value=""></input>
                                </span>
            </p>

            <p class="field " style="width:248px; ">
                <label class="" for="filiacao_pai" style="">Nome do Pai</label>
                <span class="input_alert">&nbsp;</span>
                                <span class="input " rel="filiacao_pai" style="">
                                    <input id="filiacao_pai" maxlength="255" name="filiacao_pai" style="" type="text" value=""></input>
                                </span>
            </p>

            <hr class="clear" size="1"></hr>

            <fieldset class="fieldset " id="op_conjuge" style="width:680px;">
                <legend>
                                    <span class="legend">
                                        <span class="legend_label">Dados do Conjuge</span>
                                        <span class="input_alert">&nbsp;</span>
                                    </span>
                </legend>

                <p class="field " style="width:280px; ">
                    <label class="" for="conjuge_nome" style="">Nome do Conjuge</label>
                    <span class="input_alert">&nbsp;</span>
                                    <span class="input " rel="conjuge_nome" style="">
                                        <input id="conjuge_nome" maxlength="255" name="conjuge_nome" style="" type="text" value=""></input>
                                    </span>
                </p>

                <p class="field " style="width:110px; ">
                    <label class="" for="conjuge_cpf" style="">CPF do Conjuge</label>
                    <span class="input_alert">&nbsp;</span><span class="input " rel="conjuge_cpf" style="">
                                        <input id="conjuge_cpf" mask="999.999.999-99" name="conjuge_cpf" style="" type="text" value=""></input>
                                    </span>
                </p>

                <p class="field " style="width:auto; ">
                    <label class="" for="conjuge_data_nascimento" style="">Data de Nascimento</label>
                    <span class="input_alert">&nbsp;</span>
                                    <span class="input " rel="conjuge_data_nascimento" style="">
                                        <input class=" date" id="conjuge_data_nascimento" mask="39/19/9999" name="conjuge_data_nascimento" style="" type="text" value=""></input>
                                    </span>
                </p>

                <p class="field " style="width:140px; ">
                    <label class="" for="conjuge_profissao" style="">Profissão do Conjuge</label>
                    <span class="input_alert">&nbsp;</span>
                                    <span class="input " rel="conjuge_profissao" style="">
                                        <input id="conjuge_profissao" maxlength="50" name="conjuge_profissao" style="" type="text" value=""></input>
                                    </span>
                </p>

            </fieldset>
        </div>

    </fieldset>

    <fieldset class="fieldset " id="tab_dados_gerais" style="width:240px;float:left;">
        <legend>
                            <span class="legend"><span class="legend_label">Dados Gerais</span>
                                <span class="input_alert">&nbsp;</span>
                            </span>
        </legend>

        <p class="field " style="width:110px; ">
            <label class="" style="">Recebe Email</label>
            <span class="input_alert">&nbsp;</span>
                            <span class="input radio" rel="" style="">
                                <label class="inline" style="">
                                    <input class=" required" eval="1" name="recebe_email" style="" type="radio" value="0"></input>
                                    <span style="">Não</span>
                                </label>
                                <label class="inline" style="">
                                    <input class=" required" eval="1" name="recebe_email" style="" type="radio" value="1"></input>
                                    <span style="">Sim</span>
                                </label>
                            </span>
        </p>

        <p class="field " style="width:110px; ">
            <label class="" for="valor_limite_credito" style="">Limite de Crédito</label>
            <span class="input_alert">&nbsp;</span>
                            <span class="input " rel="valor_limite_credito" style="">
                                <input id="valor_limite_credito" name="valor_limite_credito" number_format="+#.#0,[2,2]" style="" type="text" value=""></input>
                            </span>
        </p>

        <p class="field " style="width:110px; ">
            <label class="" for="saldo_para_compras" style="">Saldo para Compras</label>
            <span class="input_alert">&nbsp;</span>
                            <span class="input " rel="saldo_para_compras" style="">
                                <input id="saldo_para_compras" name="saldo_para_compras" number_format="+#.#0,[2,2]" readonly="readonly" style="" type="text" value=""></input>
                            </span>
        </p>

        <input id="foto" name="foto" type="hidden" value=""></input>
        <hr class="clear" size="1"></hr>

    </fieldset>

    <hr class="clear" size="1"></hr>

    <p class="field " style="width:239px; ">
        <label class="" for="suframa" style="">SUFRAMA</label>
        <span class="input_alert">&nbsp;</span>
                        <span class="input " rel="suframa" style="">
                            <input id="suframa" name="suframa" style="" type="text" value=""></input>
                        </span>
    </p>

    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>

</div>