<div class="tab" id="tab_dados_pessoais" ref="<img src='../../../images/data.png'> Dados Pessoais" rel="tab_dados_pessoais">

    <input id="id" name="id" type="hidden" value="" class="text" rel="seila"></input>
    <input id="empresa" name="empresa" type="hidden" value=""></input>

    <fieldset class="fieldset " style="width:15%;">
        <legend>
            <span class="legend">
                <span class="legend_label">Ativo</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:auto; ">
            <span class="input radio" rel="" style="">
                <label class="inline" style="">
                    <input class="" eval="1" name="ativo" style="" type="radio" value="0"></input>
                    <span style="">Não</span>
                </label>

            </span>
        </p>
    </fieldset>
    <fieldset class="fieldset " style="width:25%;">
        <legend>
            <span class="legend"><span class="legend_label">Tipo de cliente</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:auto; ">
            <span class="input radio" rel="" style="">
                <label class="inline" style="">
                    <input class=" required" eval="F" name="tipo" style="" type="radio" value="F"></input>
                    <span style="">Pessoa Física</span>
                </label>
                <label class="inline" style="">
                    <input class=" required" eval="F" name="tipo" style="" type="radio" value="J"></input>
                    <span style="">Pessoa Jurídica</span>
                </label>
            </span>
        </p>

    </fieldset>
    <fieldset class="fieldset " style="width:25%;">
        <legend>
            <span class="legend">
                <span class="legend_label">Origem</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:auto; ">
            <span class="input radio" rel="" style="">
                <label class="inline" style="">
                    <input class="required" eval="0" name="exterior" style="" type="radio" value="0"></input>
                    <span style="">Nacional</span>
                </label>
                <label class="inline" style="">
                    <input class=" required" eval="0" name="exterior" style="" type="radio" value="1"></input>
                    <span style="">Estrangeira</span>
                </label>
            </span>
        </p>
        <input id="flag_exterior" name="flag_exterior" type="hidden" value="0"></input>

    </fieldset>
    <fieldset class="fieldset " style="width:26.3%;">
        <legend>
            <span class="legend">
                <span class="legend_label">Data de Criação</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:95%; ">
            <span class="input " rel="data_cadastro" style="">
                <input class="center" disabled="disabled" id="data_cadastro" mask="39/19/9999" name="data_cadastro" style="" type="text" value="23/08/2015"></input>
            </span>
        </p>

    </fieldset>
    <input id="tipocliente" name="tipocliente" type="hidden" value=""></input>
    <hr class="clear" size="1"></hr>
    <fieldset class="fieldset " id="field_tipo" style="width:97%;width:65%; float:left;">
        <legend>
            <span class="legend">
                <span class="legend_label">%temp%</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:72%; ">
            <label class="" for="razao_social" style="">Razão Social</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="razao_social" style="">
                <input class="focus required" id="razao_social" maxlength="60" name="razao_social" style="" type="text" value=""></input>
            </span>
        </p>

        <div id="fisica_dados">
            <p class="field " style="width:auto; ">
                <label class="" for="cpf" style="">CPF</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="cpf" style="">
                    <input class=" cpf" id="cpf" mask="999.999.999-99" name="cpf" style="" type="text" value=""></input>
                </span>
            </p>
        </div>

        <div id="juridica_dados">
            <p class="field " style="width:auto; ">
                <label class="" for="cnpj" style="">CNPJ</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="cnpj" style="">
                    <input class="search cnpj" id="cnpj" mask="99.999.999/9999-99" name="cnpj" pstyle="width:115px;" style="" type="text" value=""></input>
                </span>
            </p>
            <input class="btn_view" id="pesquisar_cnpj" name="" style="float:left;height:23px;margin:22px 0 0;padding:0;width:33px;" title="Pesquisar dados pelo CNPJ" type="button" value=""></input>

            <p class="field " style="width:72%; ">
                <label class="" for="nome_fantasia" style="">Nome Fantasia</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="nome_fantasia" style="">
                    <input id="nome_fantasia" maxlength="255" name="nome_fantasia" style="" type="text" value=""></input>
                </span>
            </p>

            <p class="field " style="width:154px; ">
                <label class="" for="responsavel" style="">Responsável</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="responsavel" style="">
                    <input id="responsavel" maxlength="255" name="responsavel" style="" type="text" value=""></input>
                </span>
            </p>
        </div>

        <hr class="clear" size="1"></hr>
        <p class="field " style="width:170px; ">
            <label class="" for="ident_estrangeiro" style="">Identificação do Estrangeiro</label>
            <span class="input_info" style="">
                <img alt="info" class="infotip" src="http://app.tagplus.com.br/capitalponto/resources/images/icons/info.png" title="Número do passaporte ou outro documento legal para identificar a pessoa estrangeira."></img>
            </span>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="ident_estrangeiro" style="">
                <input id="ident_estrangeiro" maxlength="20" name="ident_estrangeiro" style="" type="text" value=""></input>
            </span>
        </p>

        <div id="grupo_ie">
            <p class="field " style="width:150px; ">
                <label class="" for="ie" style="">Inscrição Estadual</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="ie" style="">
                    <input id="ie" maxlength="16" name="ie" style="" type="text" value=""></input>
                </span>
            </p>

            <div style="float:left; width:65px;padding-top:22px">
                <p class="checkbox_field  block" style="">
                    <label class="" for="isento_ie" style="">
                        <input campo="ie" id="isento_ie" name="isento_ie" rel="" style="" type="checkbox" value="1"></input>
                        <span>Isento</span>
                    </label>
                </p>
            </div>
        </div>

        <div id="juridica">
            <p class="field " style="width:150px; ">
                <label class="" for="im" style="">Inscrição Municipal</label>
                <span class="input_alert">&nbsp;</span>
                <span class="input " rel="im" style="">
                    <input id="im" maxlength="20" name="im" style="" type="text" value=""></input>
                </span>
            </p>

            <div style="float:left; width:65px;padding-top:22px">
                <p class="checkbox_field  block" style="">
                    <label class="" for="isento_im" style="">
                        <input campo="im" id="isento_im" name="isento_im" rel="" style="" type="checkbox" value="1"></input>
                        <span>Isento</span>
                    </label>
                </p>
            </div>
        </div>

        <p class="field " style="width:170px; ">
            <label class="" for="cod_barra" style="">Código do Cliente</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="cod_barra" style="">
                <input id="cod_barra" maxlength="14" name="cod_barra" style="" type="text" uppercase="true" value=""></input>
            </span>
        </p>
        <span class="ean" id="ean" style="margin-top:25px" title="Gerar Código EAN">&nbsp;</span>

    </fieldset>
    <fieldset class="fieldset " id="field_contatos_principais" style="width:97%;width:30%; float:left;">
        <legend>
            <span class="legend"><span class="legend_label">Contatos Principais</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:95%; ">
            <label class="" for="email_principal_aux" style="">Email</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="email_principal_aux" style="">
                <input id="email_principal_aux" maxlength="50" name="email_principal_aux" style="" type="text" value=""></input>
            </span>
        </p>

        <p class="field " style="width:95%; ">
            <label class="" for="telefone_principal_aux" style="">Telefone</label>
            <span class="input_alert">&nbsp;</span>
            <span class="input " rel="telefone_principal_aux" style="">
                <input id="telefone_principal_aux" maxlength="14" name="telefone_principal_aux" style="" type="text" value=""></input>
            </span>
        </p>

    </fieldset>
    <fieldset class="fieldset " style="width:97%;height:90px;">
        <legend>
            <span class="legend">
                <span class="legend_label">Informação Adicional</span>
                <span class="input_alert">&nbsp;</span>
            </span>
        </legend>

        <p class="field " style="width:100%; ">
            <span class="input " rel="informacao_adicional" style="">
                <textarea cols="90" id="informacao_adicional" maxlength="4000" name="informacao_adicional" rows="25"  style="height:70px;resize: none;"></textarea>
            </span>
        </p>

    </fieldset>
    <div class="tab_navigator ">
        <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
        <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
    </div>
</div>