<?php echo $this->doctype(); ?>
<html>

<head>
    <meta http-equiv='cache-control' content='no-cache' />
    <meta http-equiv='expires' content='0' />
    <meta http-equiv='pragma' content='no-cache' />
    <meta name="robots" content="NOINDEX,NOFOLLOW" />
    <meta name="base_url" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/png" href="/images/favicon.ico" />

    <link rel="shortcut icon" href="<?php echo $this->basePath() ?>/images/favicon.ico">
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/js-core.js"></script>
    <script type="text/javascript">
        $(window).load(function() {
            setTimeout(function() {
                $('#loading').fadeOut(400, "linear");
            }, 300);
        });
    </script>
    <style>
        .text-green{
            color:#4ECDC4!important
        }
        a.normal:hover {
            cursor: default;
            color: #7e7e7e;
            font-size: 13px;
        }
        a.normal {
            cursor: default;
            font-size: 13px;
        }


        #loading {
            position: fixed;
            width: 100%;
            height: 100%;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            display: block;
            background: #F5F5F5;
            z-index: 10000;
        }

        #loading img {
            position: absolute;
            top: 50%;
            left: 50%;
            margin: -23px 0 0 -23px;
        }

        .error-notice {
            margin: 10px ; /* Making sure to keep some distance from all side */
        }

        .oaerror {
            width: 100%; /* Configure it fit in your design  */
            margin: 0 auto; /* Centering Stuff */
            background-color: #FFFFFF; /* Default background */
            padding: 20px;
            border: 1px solid #eee;
            border-left-width: 5px;
            border-radius: 3px;
            margin: 0 auto;
            font-family: 'Open Sans', sans-serif;
            font-size: 16px;
        }

        .danger {
            border-left-color: #d9534f; /* Left side border color */
            background-color: rgba(217, 83, 79, 0.1); /* Same color as the left border with reduced alpha to 0.1 */
        }

        .danger strong {
            color:  #d9534f;
        }

        .warning {
            border-left-color: #f0ad4e;
            background-color: rgba(240, 173, 78, 0.1);
        }

        .warning strong {
            color: #f0ad4e;
        }

        .info {
            border-left-color: #5bc0de;
            background-color: rgba(91, 192, 222, 0.1);
        }

        .info strong {
            color: #5bc0de;
        }

        .success {
            border-left-color: #2b542c;
            background-color: rgba(43, 84, 44, 0.1);
        }

        .success strong {
            color: #2b542c;
        }
    </style>

    <?php echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/helpers-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/elements/elements-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/fontawesome/fontawesome.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/linecons/linecons.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/snippets/snippets-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/applications/mailbox.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/layout.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/layout-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/framework-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/border-radius.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/colors.css' )?>
</head>
<body>
<div id="loading">
    <img src="<?php echo $this->basePath() ?>/assets-minified/images/spinner/loader-dark.gif" alt="Loading...">
</div>
<div class="center-vertical">
    <div class="center-content">

        <?php
        $form->setAttribute('action',$this->url('usuario-authentication',array('controller'=>'Authentication','action'=>'index')))
            ->setAttribute('id','login-validation')
            ->setAttribute('class','col-md-4 center-margin')
            ->setAttribute('autocomplete','off');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <!-- TAB LOGO -->
        <?php echo $this->partial('partials/tab_logo'); ?>
        <!-- -->

        <?php if($this->error): ?>
            <div class="row" id="error">
                <div class="error-notice">
                    <div class="oaerror danger" style="font-size: 14px">
                        <?php echo $this->message; ?>
                    </div>
                </div>
            </div>
            <script>
                setTimeout(function(){$('#error').fadeOut(3000); },5000) </script>
        <?php endif; ?>

        <?php if($this->atencao): ?>
            <div class="row" id="atencao">
                <div class="error-notice">
                    <div class="oaerror warning" style="font-size: 14px">
                        <?php echo $this->message; ?>
                    </div>
                </div>
            </div>
            <script> setTimeout(function(){$('#atencao').fadeOut(3000); },20000) </script>
        <?php endif; ?>


        <!-- TAB USUARIO SENHA -->
        <?php echo $this->partial('partials/tab_usuario_senha'); ?>
        <!-- -->

        <!-- TAB RECUPERAR SENHA -->
        <?php echo $this->partial('partials/tab_recuperar_senha'); ?>
        <!-- -->

        <?php echo $this->form()->closeTag();?>

        <!-- TAB FOOTER -->
        <?php echo $this->partial('partials/tab_footer'); ?>
        <!-- -->

    </div>

</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.css">
<script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.js"></script>
</body>
</html>
