<div class="tab" id="tab_perfil_acesso_662544494c3eee93459b37a362c61f3295cf33874" ref="Dados do funcionário" rel="tab_perfil_acesso">
  
  <input id="id_entidade" name="id_entidade" type="hidden" value></input>
  <input id="id_empresa" name="id_empresa" type="hidden" value=></input>
  <input id="id_funcionario" name="id_funcionario" type="hidden" value=></input>
  
  <div style="float:left; width:30%; margin-right:12px">
    <!-- Ativo -->
    <fieldset class="fieldset " style="width:97%;">
      
      <legend>
        <span class="legend">
          <span class="legend_label">Ativo</span>
          <span class="input_alert">&nbsp;</span>
        </span>
      </legend>

      <p class="field " style="width:auto; ">
        <span class="input radio" rel="" style="">
          
          <label class="inline">
            <input class=" required" eval="1" name="ativo" style=""  type="radio" value="0"></input>
            <span>Não</span>
          </label>
          
          <label class="inline">
            <input class=" required" eval="1" name="ativo" style="" type="radio" value="1"></input>
            <span>Sim</span>
          </label>
        
        </span>
      </p>
    
    </fieldset>
    
    <!-- Sexo -->
    <fieldset class="fieldset " style="width:97%;">
      
      <legend>
        <span class="legend">
          <span class="legend_label">Sexo</span>
          <span class="input_alert">&nbsp;</span>
        </span>
      </legend>

      <p class="field " style="width:auto; ">
        <span class="input radio" rel="" style="">
          
          <label class="inline">
            <input class=" required" eval="M" name="sexo" style="" type="radio" value="F"></input>
            <span>Feminino</span>
          </label>
          
          <label class="inline">
            <input class=" required" eval="M" name="sexo" style="" type="radio" value="M"></input>
            <span>Masculino</span>
          </label>
        
        </span>
      </p>
    </fieldset>
  </div>

  <div style="float:left; width:67%">
    
    <!-- senha_pdv -->
    <fieldset class="fieldset " style="width:97%;">
      
      <legend>
        <span class="legend">
          <span class="legend_label">Informações Pessoais</span>
          <span class="input_alert">&nbsp;</span>
        </span>
      </legend>
      
      <!-- Nome -->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="razao_social" style="width:25%">Nome completo</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Nome completo do funcionario."></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input" rel="razao_social" style="width: 67%">
          <input class="focus required nome" id="razao_social" name="razao_social" style="" type="text" value></input>
        </span>
      </p>

      <!-- CPF -->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="cpf" style="width:25%">CPF</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="CPF do funcionário.Estes dados são sigilosos e não serão compartilhados."></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="cpf" style="width: 25%">
          <input class="cpf" id="cpf" mask="999.999.999-99" name="cpf" style="" type="text" value></input>
        </span>
      </p>

    </fieldset>
   
    <hr class="clear" size="1"></hr>

    <fieldset class="fieldset " style="width:97%;">
      
      <legend>
        <span class="legend">
          <span class="legend_label">Dados de acesso</span>
          <span class="input_alert">&nbsp;</span>
        </span>
      </legend>
      
      <!-- Perfil de acesso -->
      <p class="field inline" style="width:auto; width:93% !important;">
       
       <label class="" for="id_perfil" style="width:25%">Perfil de acesso</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Relacione o funcionário a um perfil de acesso.Os perfis de acesso contem as permissões de uso ao sistema.Quando você relaciona um perfil á um usuario , este usuario passa a ter todas as permissões daquele perfil."></img>
        </span>
        
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="id_perfil" style="width: 67%">
          <input id="id_perfil" name="id_perfil" type="hidden" value></input>
          <i class="ui-autocomplete_combo" tabindex="-1"></i>
          <input 
            autosuggest="id_perfil"
            class="temp required autosuggest"
            filters="[]"
            form_title="Cadastrando Perfil de Acesso"
            form_url="<?php echo $this->basePath() ?>/senna/usuario/perfis/form"
            form_url_field="descricao"
            id="id_perfil"
            minLength="0"
            name="ac_09524703996108d363d8bcef016e26f8ee0b661740"
            new_item_info="Criar um novo registro"
            new_item_label="Cadastrar Novo"
            source="<?php echo $this->basePath() ?>/senna/usuario/perfis/getPerfilFuncionario"
            style="" type="text"
            value=""
            valueclear="true"
            valuefield="id"></input>
          <em class="autocomplete_search temp required autosuggest"></em>
        </span>
      </p>
     
      <!-- Código de Acesso-->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="codigo_acesso" style="width:25%">Login de usuário</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Informe um login de acesso ao sistema.Você pode gerar um numero aleatorio de acesso para cada usuário"></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="codigo_acesso" style="width: 67%">
          <input class=" required" id="codigo_acesso" name="codigo_acesso" style="" type="text" ></input>
        </span>
      </p>
      <span class="ean" id="ean" title="Gerar Código EAN13">&nbsp;</span>
      
      <!-- Senha -->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="senha" style="width:25%">Senha</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Informe uma senha de acesso ao sistema"></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="senha" style="width: 67%">
          <input class="" id="senha" maxLength="100" minLength="6" name="senha" requiredIf="$('#id').val()==''" style="" type="password" value></input>
        </span>
      </p>
      <span class="application_key" id="pass_pdv" title="Senha para Acesso Off-Line ao PDV">&nbsp;</span>
      
      <!-- Confirma Senha -->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="senha_confirma" style="width:25%">Confirmação de senha</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Confirme uma senha de acesso"></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="senha_confirma" style="width: 67%">
          <input class="" equalTo="#senha" id="senha_confirma" maxLength="100" minLength="6" name="senha_confirma" style="" type="password" value=""></input>
        </span>
      </p>

    </fieldset>
    
    <fieldset class="fieldset " show="inline" style="width:97%;">
      
      <legend>
        <span class="legend">
          <span class="legend_label">Dados Trabalhistas</span>
          <span class="input_alert">&nbsp;</span>
        </span>
      </legend>
     
      <!-- Setor -->
      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="id_financeiro_setor" style="width:25%">Departamento</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Selecione o departamento o qual o funcionario pertence"></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="id_financeiro_setor" style="width: 67%">
          <input id="id_financeiro_setor" name="id_financeiro_setor" type="hidden" value="1"></input>
          <i class="ui-autocomplete_combo" tabindex="-1"></i>
          <input
            autosuggest="id_financeiro_setor" 
            class=" required autosuggest" 
            filters="[]"
            form_title="Cadastrando Departamento"
            form_url="<?php echo $this->basePath() ?>/senna/cadastro/setores/form"
            form_url_field="descricao" 
            id="id_financeiro_setor" 
            minLength="0"
            name="ac_0997495059e6c4b0797dec3063c317d26479109f97"
            new_item_info="Criar um novo registro" 
            new_item_label="Cadastrar Novo"
            source="<?php echo $this->basePath() ?>/senna/cadastro/setores/getSetor"
            style="" 
            type="text" 
            value="" 
            valueclear="true"
            valuefield="id"></input>
          <em class="autocomplete_search  required autosuggest"></em>
        </span>
      </p>

    </fieldset>
    
    <fieldset class="fieldset " id="field_contatos_principais" style="width:97%;">
      
      <legend>
      <span class="legend">
        <span class="legend_label">Contatos Principais</span>
        <span class="input_alert">&nbsp;</span>
      </span>
      </legend>



      <p class="field inline" style="width:auto; width:93% !important;">
        <label class="" for="telefone_principal_aux" style="width:25%">Telefone</label>
        <span class="input_info">
          <img alt="info" class="infotip" src="/images/info.png"  title="Informe um telefone de contato do funcionario."></img>
        </span>
        <span class="input_alert">&nbsp;</span>
        <span class="input " rel="telefone_principal_aux" style="width: 67%">
          <input id="telefone_principal_aux" maxlength="14" name="telefone_principal_aux" style="" type="text" value=""></input>
        </span>
      </p>
    </fieldset>
  </div>
  <div class="tab_navigator ">
    <input class="prevTab" name="Voltar" type="button" value="Voltar"></input>&nbsp;&nbsp;
    <input class="nextTab" name="Continuar" type="button" value="Continuar"></input>
  </div>
</div>