<?php
/*
 * MODELO DE JSON DE RETORNO
 * {
 * "page":1,
 * "total":"2",
 * "data":[{
 * "id":"10", // id da categoria
 * "descricao":"Crachas", // nome da caregoria ou sub categoria
 * "id_produto_categoria":null,// id da categoria pai caso houver
 * "localizacao":"", // localizacao
 * "subcategoria":"" // Nome da categoria pai
 * },{
 * "id":"11",
 * "descricao":"Crachas de platico",
 * "id_produto_categoria":"10",
 * "localizacao":"",
 * "subcategoria":"Crachas"
 * }]
 * }
 */
$rows = array("page"=>(int)$this->page,'total'=>'', 'data'=>array()); 
foreach ( $this->data as $key => $entity ) :
	foreach ( $entity as $k => $e ) :
		$row [$k] = $e;
	endforeach;
	array_push ( $rows['data'], $row );
endforeach;
	$rows['total']="".$this->registos."";

print json_encode($rows);
