<?php define('__ID_USUARIO__', $this->UsuarioIdentity("Usuario")->getId());define('__SEXO__', $this->UsuarioIdentity("Usuario")->getSexo());define('__NOME_USUARIO__', $this->UsuarioIdentity("Usuario")->getNome());?>
<?php echo $this->doctype(); ?>
<html>
<head>
    <meta http-equiv='cache-control' content='no-cache'/>
    <meta http-equiv='expires' content='0'/>
    <meta http-equiv='pragma' content='no-cache'/>
    <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    <meta name="base_url" content=""/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <!-- Script da pagina js/code -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/mootools-1.2-core.js')
        ->appendFile($this->basePath() . '/js/mootools-1.2-more.js')
        ->appendFile($this->basePath() . '/js/Core.js')
        ->appendFile($this->basePath() . '/js/Window.js')
        ->appendFile($this->basePath() . '/js/Modal.js')
        ->appendFile($this->basePath() . '/js/mocha-ext.js')
        ->appendFile($this->basePath() . '/js/base.js')
        ->appendFile($this->basePath() . '/js/jquery/core.js')
        ->appendFile($this->basePath() . '/js/jquery/debug.js')
        ->appendFile($this->basePath() . '/js/jquery/dump.js')
        ->appendFile($this->basePath() . '/js/jquery/bt.js')
        ->appendFile($this->basePath() . '/js/jquery/validate.js')
        ->appendFile($this->basePath() . '/js/jquery/tab.js')
        ->appendFile($this->basePath() . '/js/jquery/tablestyle.js')
        ->appendFile($this->basePath() . '/js/jquery/clonefield.js')
        ->appendFile($this->basePath() . '/js/jquery/maskedinput.js')
        ->appendFile($this->basePath() . '/js/sexyalertbox.js')
        ->appendFile($this->basePath() . '/js/jquery/uppercase.js')
        ->appendFile($this->basePath() . '/js/jquery/date.js')
        ->appendFile($this->basePath() . '/js/jquery/datepicker.js')
        ->appendFile($this->basePath() . '/js/jquery/autocomplete.js')
        ->appendFile($this->basePath() . '/js/jquery/readonly.js')
        ->appendFile($this->basePath() . '/js/jquery/confirm_message.js')
        ->appendFile($this->basePath() . '/js/jquery/livequery.js')
        ->appendFile($this->basePath() . '/js/forms.js')
        ->appendFile($this->basePath() . '/js/jquery/priceformat.js')
        ->appendFile($this->basePath() . '/js/jquery/cloneform.js')
        ->appendFile($this->basePath() . '/js/jquery/ui.js')
        ->appendFile($this->basePath() . '/js/script_usuario_form_view.js') ?>

    <!-- Estilos da pagina Css/code -->
    <?php echo $this->headLink()
        //->appendStylesheet($this->basePath() . '/css/noprint.css')
        ->appendStylesheet($this->basePath() . '/css/glyphs.css')
        ->appendStylesheet($this->basePath() . '/css/loader.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/style_tagplus.css')
        ->appendStylesheet($this->basePath() . '/css/sexyalertbox.css')
        ->appendStylesheet($this->basePath() . '/css/datepicker.css')
        ->appendStylesheet($this->basePath() . '/css/cloneform.css')
        ->appendStylesheet($this->basePath() . '/css/jqueryui.css')
        ->appendStylesheet($this->basePath() . '/css/clonetable.css') ?>

    <style>

        .tab_selector li span {
            display: block;
            float: left;
            margin: 5px 0 0;!important;
            color: #666;
            border: 0;
            font-size: 10px;
            font-weight: 100;
        }

    </style>
</head>
<body>

<div id="loader">
    <div class="loader-text">
        <span class='carregando'>Carregando ...</span>
        <span class='enviando' style="display: none">Enviando ...</span>
    </div>
    <div class="loader-bg">&nbsp;</div>
</div>

<div id="tela" style='height:auto !important;'>
    <div id="conteudo" style='position:absolute;top:0px;bottom:0px;height:auto !important;'>

        <!--INICIO DO FORMULARIO-->
        <?php
        $form->setAttribute('action', $this->url('usuario-listar/default', array('controller' => 'info', 'action' => 'save')));
        $form->setAttribute('windowId', $this->url('usuario-listar/default', array('controller' => 'info', 'action' => 'form')));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <div class="form_actions" id="form_actions">
            <input class="save" name="Salvar" saveWindowForm="true" type="submit" value="Salvar"></input>
        </div>

        <input id="id" name="id" type="hidden" value="<?php echo __ID_USUARIO__ ?>"></input>

        <div class="form_fields" id="form_fields">

            <!-- TAB DADOS GERAIS -->
            <?php echo $this->partial('partials/tab_dados_gerais_view'); ?>
            <!-- -->

            <!-- TAB CONTATOS-->
             <?php echo $this->partial('partials/tab_contatos_view'); ?>
            <!-- -->

            <!-- TAB ENDERECOS -->
            <?php echo $this->partial('partials/tab_enderecos_view'); ?>
            <!-- -->

            <!-- TAB DEPENDENTES -->
            <?php echo $this->partial('partials/tab_dependentes_view'); ?>
            <!-- -->

        </div>

        <?php echo $this->form()->closeTag(); ?>
        <!--FIM DO FORMULARIO-->
    </div>
</div>

<div id="footer"></div>
</body>
</html>