<?php $data =  new \DateTime("now");
print_r($data);
?>
<?php echo $this->doctype(); ?>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Senna :: Grupo Capital Ponto</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">

    <link rel="shortcut icon" href="<?php echo $this->basePath() ?>/images/favicon.ico">
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/js-core.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/script_pagina.js"></script>
    <style>
        .text-green{
            color:#4ECDC4!important
        }
        a.normal:hover {
            cursor: default;
            color: #7e7e7e;
            font-size: 13px;
        }
        a.normal {
            cursor: default;
            font-size: 13px;
        }


        #loading {
            position: fixed;
            width: 100%;
            height: 100%;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            display: block;
            background: #F5F5F5;
            z-index: 10000;
        }

        #loading img {
            position: absolute;
            top: 50%;
            left: 50%;
            margin: -23px 0 0 -23px;
        }
    </style>

    <?php echo $this->headLink ()->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/helpers-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/elements/elements-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/fontawesome/fontawesome.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/icons/linecons/linecons.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/snippets/snippets-all.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/applications/mailbox.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/layout.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/layout-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/default/framework-color.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/themes/supina/border-radius.css' )
        ->appendStylesheet ( $this->basePath () . '/assets-minified/helpers/colors.css' )?>
</head>
<body>
<div id="loading"><img src="<?php echo $this->basePath() ?>/assets-minified/images/spinner/loader-dark.gif" alt="Loading..."></div>
<div class="center-vertical">
    <div class="center-content">
        <?php
        $form->setAttribute('action',$this->url('usuario-authentication',array('controller'=>'Authentication','action'=>'index')))
            ->setAttribute('id','login-validation')
            ->setAttribute('class','col-md-4 center-margin')
            ->setAttribute('autocomplete','off');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <!-- TAB LOGO -->
        <?php echo $this->partial('partials/tab_logo'); ?>
        <!-- -->

        <!-- TAB USUARIO SENHA -->
        <?php echo $this->partial('partials/tab_usuario_senha'); ?>
        <!-- -->

        <!-- TAB RECUPERAR SENHA -->
        <?php echo $this->partial('partials/tab_recuperar_senha'); ?>
        <!-- -->

        <?php echo $this->form()->closeTag();?>

        <!-- TAB FOOTER -->
        <?php echo $this->partial('partials/tab_footer'); ?>
        <!-- -->

    </div>

</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.css">
<script type="text/javascript" src="<?php echo $this->basePath() ?>/assets-minified/demo-widgets.js"></script>
</body>
</html>