<?php $perfil = $this->UserIdentity("Usuario")->getNomePerfil()?$this->UserIdentity("Usuario")->getNomePerfil():"nada";  ?>

<h1>Usuarios</h1>

<br />

<?php if($this->PermissaoUsuario($perfil,"Cadastro Usuario","1")): ?>
<p>
    <a href="<?php echo $this->url('usuario-admin/default',array('action'=>'new')); ?>">Novo</a>
</p>
<?php endif; ?>


<?php if($this->PermissaoUsuario($perfil,"Cadastro Usuario","1")): ?>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Perfil</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>

    
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getNome(); ?></td>
        <td><?php echo $entity->getEmail(); ?></td>
        <td><?php echo $entity->getPerfil()->getNome(); ?></td>
        <td>
            <?php if($this->PermissaoUsuario($perfil,"Cadastro Usuario","1")): ?>

                <a href="<?php echo $this->url('usuario-admin/default', array('controller'=>'usuarios','action'=>'edit','id'=>$entity->getId()));?>">Editar</a>

            <?php endif; ?>

            <?php if($this->PermissaoUsuario($perfil,"Cadastro Usuario","1")): ?>

                <a href="<?php echo $this->url('usuario-admin/default', array('controller'=>'usuarios','action'=>'delete','id'=>$entity->getId()));?>">Delete</a>

            <?php endif; ?>
            
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>